/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APCNTotal
 */
export interface APCNTotal {
    /**
     * 
     * @type {number}
     * @memberof APCNTotal
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof APCNTotal
     */
    vat?: number;
    /**
     * 
     * @type {number}
     * @memberof APCNTotal
     */
    total?: number;
}

/**
 * Check if a given object implements the APCNTotal interface.
 */
export function instanceOfAPCNTotal(value: object): value is APCNTotal {
    return true;
}

export function APCNTotalFromJSON(json: any): APCNTotal {
    return APCNTotalFromJSONTyped(json, false);
}

export function APCNTotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): APCNTotal {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'vat': json['vat'] == null ? undefined : json['vat'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function APCNTotalToJSON(json: any): APCNTotal {
    return APCNTotalToJSONTyped(json, false);
}

export function APCNTotalToJSONTyped(value?: APCNTotal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'vat': value['vat'],
        'total': value['total'],
    };
}

