/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APCNSupplierDetail
 */
export interface APCNSupplierDetail {
    /**
     * 
     * @type {Date}
     * @memberof APCNSupplierDetail
     */
    createDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof APCNSupplierDetail
     */
    rebateCode?: string;
    /**
     * 
     * @type {string}
     * @memberof APCNSupplierDetail
     */
    supplierId?: string;
    /**
     * 
     * @type {string}
     * @memberof APCNSupplierDetail
     */
    supplierCode?: string;
    /**
     * 
     * @type {string}
     * @memberof APCNSupplierDetail
     */
    taxPayerId?: string;
    /**
     * 
     * @type {string}
     * @memberof APCNSupplierDetail
     */
    revenueBranchCode?: string;
    /**
     * 
     * @type {string}
     * @memberof APCNSupplierDetail
     */
    supplierName?: string;
    /**
     * 
     * @type {string}
     * @memberof APCNSupplierDetail
     */
    fullAddress?: string;
    /**
     * 
     * @type {number}
     * @memberof APCNSupplierDetail
     */
    provinceId?: number;
    /**
     * 
     * @type {number}
     * @memberof APCNSupplierDetail
     */
    districtId?: number;
    /**
     * 
     * @type {number}
     * @memberof APCNSupplierDetail
     */
    subDistrictId?: number;
    /**
     * 
     * @type {string}
     * @memberof APCNSupplierDetail
     */
    zipCode?: string;
    /**
     * 
     * @type {string}
     * @memberof APCNSupplierDetail
     */
    telephone?: string;
    /**
     * 
     * @type {string}
     * @memberof APCNSupplierDetail
     */
    email?: string;
}

/**
 * Check if a given object implements the APCNSupplierDetail interface.
 */
export function instanceOfAPCNSupplierDetail(value: object): value is APCNSupplierDetail {
    return true;
}

export function APCNSupplierDetailFromJSON(json: any): APCNSupplierDetail {
    return APCNSupplierDetailFromJSONTyped(json, false);
}

export function APCNSupplierDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): APCNSupplierDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'createDate': json['create_date'] == null ? undefined : (new Date(json['create_date'])),
        'rebateCode': json['rebate_code'] == null ? undefined : json['rebate_code'],
        'supplierId': json['supplier_id'] == null ? undefined : json['supplier_id'],
        'supplierCode': json['supplier_code'] == null ? undefined : json['supplier_code'],
        'taxPayerId': json['tax_payer_id'] == null ? undefined : json['tax_payer_id'],
        'revenueBranchCode': json['revenue_branch_code'] == null ? undefined : json['revenue_branch_code'],
        'supplierName': json['supplier_name'] == null ? undefined : json['supplier_name'],
        'fullAddress': json['full_address'] == null ? undefined : json['full_address'],
        'provinceId': json['province_id'] == null ? undefined : json['province_id'],
        'districtId': json['district_id'] == null ? undefined : json['district_id'],
        'subDistrictId': json['sub_district_id'] == null ? undefined : json['sub_district_id'],
        'zipCode': json['zip_code'] == null ? undefined : json['zip_code'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function APCNSupplierDetailToJSON(json: any): APCNSupplierDetail {
    return APCNSupplierDetailToJSONTyped(json, false);
}

export function APCNSupplierDetailToJSONTyped(value?: APCNSupplierDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'create_date': value['createDate'] == null ? undefined : ((value['createDate']).toISOString()),
        'rebate_code': value['rebateCode'],
        'supplier_id': value['supplierId'],
        'supplier_code': value['supplierCode'],
        'tax_payer_id': value['taxPayerId'],
        'revenue_branch_code': value['revenueBranchCode'],
        'supplier_name': value['supplierName'],
        'full_address': value['fullAddress'],
        'province_id': value['provinceId'],
        'district_id': value['districtId'],
        'sub_district_id': value['subDistrictId'],
        'zip_code': value['zipCode'],
        'telephone': value['telephone'],
        'email': value['email'],
    };
}

