/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttachmentModel } from './AttachmentModel';
import {
    AttachmentModelFromJSON,
    AttachmentModelFromJSONTyped,
    AttachmentModelToJSON,
    AttachmentModelToJSONTyped,
} from './AttachmentModel';
import type { ApprovalOMSOPInvoiceModel } from './ApprovalOMSOPInvoiceModel';
import {
    ApprovalOMSOPInvoiceModelFromJSON,
    ApprovalOMSOPInvoiceModelFromJSONTyped,
    ApprovalOMSOPInvoiceModelToJSON,
    ApprovalOMSOPInvoiceModelToJSONTyped,
} from './ApprovalOMSOPInvoiceModel';
import type { ApprovalARCNCustomerDetailModel } from './ApprovalARCNCustomerDetailModel';
import {
    ApprovalARCNCustomerDetailModelFromJSON,
    ApprovalARCNCustomerDetailModelFromJSONTyped,
    ApprovalARCNCustomerDetailModelToJSON,
    ApprovalARCNCustomerDetailModelToJSONTyped,
} from './ApprovalARCNCustomerDetailModel';
import type { TaxWithholdingModel } from './TaxWithholdingModel';
import {
    TaxWithholdingModelFromJSON,
    TaxWithholdingModelFromJSONTyped,
    TaxWithholdingModelToJSON,
    TaxWithholdingModelToJSONTyped,
} from './TaxWithholdingModel';
import type { TransactionHistoryModel } from './TransactionHistoryModel';
import {
    TransactionHistoryModelFromJSON,
    TransactionHistoryModelFromJSONTyped,
    TransactionHistoryModelToJSON,
    TransactionHistoryModelToJSONTyped,
} from './TransactionHistoryModel';
import type { PaymentSOPStatus } from './PaymentSOPStatus';
import {
    PaymentSOPStatusFromJSON,
    PaymentSOPStatusFromJSONTyped,
    PaymentSOPStatusToJSON,
    PaymentSOPStatusToJSONTyped,
} from './PaymentSOPStatus';
import type { VoucherModel } from './VoucherModel';
import {
    VoucherModelFromJSON,
    VoucherModelFromJSONTyped,
    VoucherModelToJSON,
    VoucherModelToJSONTyped,
} from './VoucherModel';

/**
 * 
 * @export
 * @interface ApprovalOMSOPDetailModel
 */
export interface ApprovalOMSOPDetailModel {
    /**
     * 
     * @type {number}
     * @memberof ApprovalOMSOPDetailModel
     */
    trnSopPaymentId?: number;
    /**
     * 
     * @type {PaymentSOPStatus}
     * @memberof ApprovalOMSOPDetailModel
     */
    paymentSopStatus?: PaymentSOPStatus;
    /**
     * 
     * @type {string}
     * @memberof ApprovalOMSOPDetailModel
     */
    paymentSopStatusName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalOMSOPDetailModel
     */
    projectCode?: string;
    /**
     * 
     * @type {number}
     * @memberof ApprovalOMSOPDetailModel
     */
    paymentSopMonth?: number;
    /**
     * 
     * @type {string}
     * @memberof ApprovalOMSOPDetailModel
     */
    paymentSopMonthName?: string;
    /**
     * 
     * @type {number}
     * @memberof ApprovalOMSOPDetailModel
     */
    paymentSopYear?: number;
    /**
     * 
     * @type {string}
     * @memberof ApprovalOMSOPDetailModel
     */
    partnerName?: string;
    /**
     * 
     * @type {number}
     * @memberof ApprovalOMSOPDetailModel
     */
    paymentType?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalOMSOPDetailModel
     */
    jobType?: number;
    /**
     * 
     * @type {string}
     * @memberof ApprovalOMSOPDetailModel
     */
    jobTypeName?: string;
    /**
     * 
     * @type {ApprovalARCNCustomerDetailModel}
     * @memberof ApprovalOMSOPDetailModel
     */
    partnerDetail?: ApprovalARCNCustomerDetailModel;
    /**
     * 
     * @type {Array<ApprovalOMSOPInvoiceModel>}
     * @memberof ApprovalOMSOPDetailModel
     */
    invoices?: Array<ApprovalOMSOPInvoiceModel>;
    /**
     * 
     * @type {Array<VoucherModel>}
     * @memberof ApprovalOMSOPDetailModel
     */
    voucher?: Array<VoucherModel>;
    /**
     * 
     * @type {Array<TransactionHistoryModel>}
     * @memberof ApprovalOMSOPDetailModel
     */
    history?: Array<TransactionHistoryModel>;
    /**
     * 
     * @type {TaxWithholdingModel}
     * @memberof ApprovalOMSOPDetailModel
     */
    taxWithholding?: TaxWithholdingModel;
    /**
     * 
     * @type {number}
     * @memberof ApprovalOMSOPDetailModel
     */
    sopPaymentPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalOMSOPDetailModel
     */
    sopPaymentVatPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalOMSOPDetailModel
     */
    sopPaymentTotalPrice?: number;
    /**
     * 
     * @type {Date}
     * @memberof ApprovalOMSOPDetailModel
     */
    createDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof ApprovalOMSOPDetailModel
     */
    workflowId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalOMSOPDetailModel
     */
    currentStepId?: number;
    /**
     * 
     * @type {string}
     * @memberof ApprovalOMSOPDetailModel
     */
    paymentSopRemark?: string;
    /**
     * 
     * @type {Array<AttachmentModel>}
     * @memberof ApprovalOMSOPDetailModel
     */
    attachment?: Array<AttachmentModel>;
}



/**
 * Check if a given object implements the ApprovalOMSOPDetailModel interface.
 */
export function instanceOfApprovalOMSOPDetailModel(value: object): value is ApprovalOMSOPDetailModel {
    return true;
}

export function ApprovalOMSOPDetailModelFromJSON(json: any): ApprovalOMSOPDetailModel {
    return ApprovalOMSOPDetailModelFromJSONTyped(json, false);
}

export function ApprovalOMSOPDetailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovalOMSOPDetailModel {
    if (json == null) {
        return json;
    }
    return {
        
        'trnSopPaymentId': json['trn_sop_payment_id'] == null ? undefined : json['trn_sop_payment_id'],
        'paymentSopStatus': json['payment_sop_status'] == null ? undefined : PaymentSOPStatusFromJSON(json['payment_sop_status']),
        'paymentSopStatusName': json['payment_sop_status_name'] == null ? undefined : json['payment_sop_status_name'],
        'projectCode': json['project_code'] == null ? undefined : json['project_code'],
        'paymentSopMonth': json['payment_sop_month'] == null ? undefined : json['payment_sop_month'],
        'paymentSopMonthName': json['payment_sop_month_name'] == null ? undefined : json['payment_sop_month_name'],
        'paymentSopYear': json['payment_sop_year'] == null ? undefined : json['payment_sop_year'],
        'partnerName': json['partner_name'] == null ? undefined : json['partner_name'],
        'paymentType': json['payment_type'] == null ? undefined : json['payment_type'],
        'jobType': json['job_type'] == null ? undefined : json['job_type'],
        'jobTypeName': json['job_type_name'] == null ? undefined : json['job_type_name'],
        'partnerDetail': json['partner_detail'] == null ? undefined : ApprovalARCNCustomerDetailModelFromJSON(json['partner_detail']),
        'invoices': json['invoices'] == null ? undefined : ((json['invoices'] as Array<any>).map(ApprovalOMSOPInvoiceModelFromJSON)),
        'voucher': json['voucher'] == null ? undefined : ((json['voucher'] as Array<any>).map(VoucherModelFromJSON)),
        'history': json['history'] == null ? undefined : ((json['history'] as Array<any>).map(TransactionHistoryModelFromJSON)),
        'taxWithholding': json['taxWithholding'] == null ? undefined : TaxWithholdingModelFromJSON(json['taxWithholding']),
        'sopPaymentPrice': json['sop_payment_price'] == null ? undefined : json['sop_payment_price'],
        'sopPaymentVatPrice': json['sop_payment_vat_price'] == null ? undefined : json['sop_payment_vat_price'],
        'sopPaymentTotalPrice': json['sop_payment_total_price'] == null ? undefined : json['sop_payment_total_price'],
        'createDate': json['create_date'] == null ? undefined : (new Date(json['create_date'])),
        'workflowId': json['workflow_id'] == null ? undefined : json['workflow_id'],
        'currentStepId': json['current_step_id'] == null ? undefined : json['current_step_id'],
        'paymentSopRemark': json['payment_sop_remark'] == null ? undefined : json['payment_sop_remark'],
        'attachment': json['attachment'] == null ? undefined : ((json['attachment'] as Array<any>).map(AttachmentModelFromJSON)),
    };
}

export function ApprovalOMSOPDetailModelToJSON(json: any): ApprovalOMSOPDetailModel {
    return ApprovalOMSOPDetailModelToJSONTyped(json, false);
}

export function ApprovalOMSOPDetailModelToJSONTyped(value?: ApprovalOMSOPDetailModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trn_sop_payment_id': value['trnSopPaymentId'],
        'payment_sop_status': PaymentSOPStatusToJSON(value['paymentSopStatus']),
        'payment_sop_status_name': value['paymentSopStatusName'],
        'project_code': value['projectCode'],
        'payment_sop_month': value['paymentSopMonth'],
        'payment_sop_month_name': value['paymentSopMonthName'],
        'payment_sop_year': value['paymentSopYear'],
        'partner_name': value['partnerName'],
        'payment_type': value['paymentType'],
        'job_type': value['jobType'],
        'job_type_name': value['jobTypeName'],
        'partner_detail': ApprovalARCNCustomerDetailModelToJSON(value['partnerDetail']),
        'invoices': value['invoices'] == null ? undefined : ((value['invoices'] as Array<any>).map(ApprovalOMSOPInvoiceModelToJSON)),
        'voucher': value['voucher'] == null ? undefined : ((value['voucher'] as Array<any>).map(VoucherModelToJSON)),
        'history': value['history'] == null ? undefined : ((value['history'] as Array<any>).map(TransactionHistoryModelToJSON)),
        'taxWithholding': TaxWithholdingModelToJSON(value['taxWithholding']),
        'sop_payment_price': value['sopPaymentPrice'],
        'sop_payment_vat_price': value['sopPaymentVatPrice'],
        'sop_payment_total_price': value['sopPaymentTotalPrice'],
        'create_date': value['createDate'] == null ? undefined : ((value['createDate']).toISOString()),
        'workflow_id': value['workflowId'],
        'current_step_id': value['currentStepId'],
        'payment_sop_remark': value['paymentSopRemark'],
        'attachment': value['attachment'] == null ? undefined : ((value['attachment'] as Array<any>).map(AttachmentModelToJSON)),
    };
}

