/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseCountStatusModel } from './BaseCountStatusModel';
import {
    BaseCountStatusModelFromJSON,
    BaseCountStatusModelFromJSONTyped,
    BaseCountStatusModelToJSON,
    BaseCountStatusModelToJSONTyped,
} from './BaseCountStatusModel';
import type { ApprovalARCNInHouseModel } from './ApprovalARCNInHouseModel';
import {
    ApprovalARCNInHouseModelFromJSON,
    ApprovalARCNInHouseModelFromJSONTyped,
    ApprovalARCNInHouseModelToJSON,
    ApprovalARCNInHouseModelToJSONTyped,
} from './ApprovalARCNInHouseModel';

/**
 * 
 * @export
 * @interface ApprovalARCNInHouseResponseModel
 */
export interface ApprovalARCNInHouseResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof ApprovalARCNInHouseResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApprovalARCNInHouseResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNInHouseResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNInHouseResponseModel
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNInHouseResponseModel
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNInHouseResponseModel
     */
    pageAll?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNInHouseResponseModel
     */
    totalRecord?: number;
    /**
     * 
     * @type {Array<ApprovalARCNInHouseModel>}
     * @memberof ApprovalARCNInHouseResponseModel
     */
    data?: Array<ApprovalARCNInHouseModel>;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNInHouseResponseModel
     */
    workflowId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNInHouseResponseModel
     */
    approvalTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNInHouseResponseModel
     */
    approvalConfirmed?: number;
    /**
     * 
     * @type {Array<BaseCountStatusModel>}
     * @memberof ApprovalARCNInHouseResponseModel
     */
    countStatusList?: Array<BaseCountStatusModel>;
}

/**
 * Check if a given object implements the ApprovalARCNInHouseResponseModel interface.
 */
export function instanceOfApprovalARCNInHouseResponseModel(value: object): value is ApprovalARCNInHouseResponseModel {
    return true;
}

export function ApprovalARCNInHouseResponseModelFromJSON(json: any): ApprovalARCNInHouseResponseModel {
    return ApprovalARCNInHouseResponseModelFromJSONTyped(json, false);
}

export function ApprovalARCNInHouseResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovalARCNInHouseResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'pageIndex': json['pageIndex'] == null ? undefined : json['pageIndex'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageAll': json['pageAll'] == null ? undefined : json['pageAll'],
        'totalRecord': json['totalRecord'] == null ? undefined : json['totalRecord'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ApprovalARCNInHouseModelFromJSON)),
        'workflowId': json['workflow_id'] == null ? undefined : json['workflow_id'],
        'approvalTotal': json['approval_total'] == null ? undefined : json['approval_total'],
        'approvalConfirmed': json['approval_confirmed'] == null ? undefined : json['approval_confirmed'],
        'countStatusList': json['count_status_list'] == null ? undefined : ((json['count_status_list'] as Array<any>).map(BaseCountStatusModelFromJSON)),
    };
}

export function ApprovalARCNInHouseResponseModelToJSON(json: any): ApprovalARCNInHouseResponseModel {
    return ApprovalARCNInHouseResponseModelToJSONTyped(json, false);
}

export function ApprovalARCNInHouseResponseModelToJSONTyped(value?: ApprovalARCNInHouseResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'pageIndex': value['pageIndex'],
        'pageSize': value['pageSize'],
        'pageAll': value['pageAll'],
        'totalRecord': value['totalRecord'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ApprovalARCNInHouseModelToJSON)),
        'workflow_id': value['workflowId'],
        'approval_total': value['approvalTotal'],
        'approval_confirmed': value['approvalConfirmed'],
        'count_status_list': value['countStatusList'] == null ? undefined : ((value['countStatusList'] as Array<any>).map(BaseCountStatusModelToJSON)),
    };
}

