/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseCountStatusModel } from './BaseCountStatusModel';
import {
    BaseCountStatusModelFromJSON,
    BaseCountStatusModelFromJSONTyped,
    BaseCountStatusModelToJSON,
    BaseCountStatusModelToJSONTyped,
} from './BaseCountStatusModel';
import type { ApprovalAPCNModel } from './ApprovalAPCNModel';
import {
    ApprovalAPCNModelFromJSON,
    ApprovalAPCNModelFromJSONTyped,
    ApprovalAPCNModelToJSON,
    ApprovalAPCNModelToJSONTyped,
} from './ApprovalAPCNModel';

/**
 * 
 * @export
 * @interface ApprovalAPCNResponseModel
 */
export interface ApprovalAPCNResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof ApprovalAPCNResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApprovalAPCNResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNResponseModel
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNResponseModel
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNResponseModel
     */
    pageAll?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNResponseModel
     */
    totalRecord?: number;
    /**
     * 
     * @type {Array<ApprovalAPCNModel>}
     * @memberof ApprovalAPCNResponseModel
     */
    data?: Array<ApprovalAPCNModel>;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNResponseModel
     */
    workflowId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNResponseModel
     */
    approvalTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNResponseModel
     */
    approvalConfirmed?: number;
    /**
     * 
     * @type {Array<BaseCountStatusModel>}
     * @memberof ApprovalAPCNResponseModel
     */
    countStatusList?: Array<BaseCountStatusModel>;
}

/**
 * Check if a given object implements the ApprovalAPCNResponseModel interface.
 */
export function instanceOfApprovalAPCNResponseModel(value: object): value is ApprovalAPCNResponseModel {
    return true;
}

export function ApprovalAPCNResponseModelFromJSON(json: any): ApprovalAPCNResponseModel {
    return ApprovalAPCNResponseModelFromJSONTyped(json, false);
}

export function ApprovalAPCNResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovalAPCNResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'pageIndex': json['pageIndex'] == null ? undefined : json['pageIndex'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageAll': json['pageAll'] == null ? undefined : json['pageAll'],
        'totalRecord': json['totalRecord'] == null ? undefined : json['totalRecord'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ApprovalAPCNModelFromJSON)),
        'workflowId': json['workflow_id'] == null ? undefined : json['workflow_id'],
        'approvalTotal': json['approval_total'] == null ? undefined : json['approval_total'],
        'approvalConfirmed': json['approval_confirmed'] == null ? undefined : json['approval_confirmed'],
        'countStatusList': json['count_status_list'] == null ? undefined : ((json['count_status_list'] as Array<any>).map(BaseCountStatusModelFromJSON)),
    };
}

export function ApprovalAPCNResponseModelToJSON(json: any): ApprovalAPCNResponseModel {
    return ApprovalAPCNResponseModelToJSONTyped(json, false);
}

export function ApprovalAPCNResponseModelToJSONTyped(value?: ApprovalAPCNResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'pageIndex': value['pageIndex'],
        'pageSize': value['pageSize'],
        'pageAll': value['pageAll'],
        'totalRecord': value['totalRecord'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ApprovalAPCNModelToJSON)),
        'workflow_id': value['workflowId'],
        'approval_total': value['approvalTotal'],
        'approval_confirmed': value['approvalConfirmed'],
        'count_status_list': value['countStatusList'] == null ? undefined : ((value['countStatusList'] as Array<any>).map(BaseCountStatusModelToJSON)),
    };
}

