/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APCNstatus } from './APCNstatus';
import {
    APCNstatusFromJSON,
    APCNstatusFromJSONTyped,
    APCNstatusToJSON,
    APCNstatusToJSONTyped,
} from './APCNstatus';

/**
 * 
 * @export
 * @interface ApprovalAPCNModel
 */
export interface ApprovalAPCNModel {
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNModel
     */
    rowNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNModel
     */
    companyId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNModel
     */
    organizationId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNModel
     */
    ownerUserId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNModel
     */
    rbtCnapId?: number;
    /**
     * 
     * @type {string}
     * @memberof ApprovalAPCNModel
     */
    rebateCode?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApprovalAPCNModel
     */
    cnDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ApprovalAPCNModel
     */
    brandName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalAPCNModel
     */
    cnNo?: string;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNModel
     */
    rebateAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNModel
     */
    cnAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNModel
     */
    vat?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNModel
     */
    amountIncludeVat?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNModel
     */
    workflowId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalAPCNModel
     */
    currentStepId?: number;
    /**
     * 
     * @type {APCNstatus}
     * @memberof ApprovalAPCNModel
     */
    trnStatus?: APCNstatus;
}



/**
 * Check if a given object implements the ApprovalAPCNModel interface.
 */
export function instanceOfApprovalAPCNModel(value: object): value is ApprovalAPCNModel {
    return true;
}

export function ApprovalAPCNModelFromJSON(json: any): ApprovalAPCNModel {
    return ApprovalAPCNModelFromJSONTyped(json, false);
}

export function ApprovalAPCNModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovalAPCNModel {
    if (json == null) {
        return json;
    }
    return {
        
        'rowNumber': json['row_number'] == null ? undefined : json['row_number'],
        'companyId': json['company_id'] == null ? undefined : json['company_id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'ownerUserId': json['owner_user_id'] == null ? undefined : json['owner_user_id'],
        'rbtCnapId': json['rbt_cnap_id'] == null ? undefined : json['rbt_cnap_id'],
        'rebateCode': json['rebate_code'] == null ? undefined : json['rebate_code'],
        'cnDate': json['cn_date'] == null ? undefined : (new Date(json['cn_date'])),
        'brandName': json['brand_name'] == null ? undefined : json['brand_name'],
        'cnNo': json['cn_no'] == null ? undefined : json['cn_no'],
        'rebateAmount': json['rebate_amount'] == null ? undefined : json['rebate_amount'],
        'cnAmount': json['cn_amount'] == null ? undefined : json['cn_amount'],
        'vat': json['vat'] == null ? undefined : json['vat'],
        'amountIncludeVat': json['amount_include_vat'] == null ? undefined : json['amount_include_vat'],
        'workflowId': json['workflow_id'] == null ? undefined : json['workflow_id'],
        'currentStepId': json['current_step_id'] == null ? undefined : json['current_step_id'],
        'trnStatus': json['trn_status'] == null ? undefined : APCNstatusFromJSON(json['trn_status']),
    };
}

export function ApprovalAPCNModelToJSON(json: any): ApprovalAPCNModel {
    return ApprovalAPCNModelToJSONTyped(json, false);
}

export function ApprovalAPCNModelToJSONTyped(value?: ApprovalAPCNModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row_number': value['rowNumber'],
        'company_id': value['companyId'],
        'organization_id': value['organizationId'],
        'owner_user_id': value['ownerUserId'],
        'rbt_cnap_id': value['rbtCnapId'],
        'rebate_code': value['rebateCode'],
        'cn_date': value['cnDate'] == null ? undefined : ((value['cnDate']).toISOString()),
        'brand_name': value['brandName'],
        'cn_no': value['cnNo'],
        'rebate_amount': value['rebateAmount'],
        'cn_amount': value['cnAmount'],
        'vat': value['vat'],
        'amount_include_vat': value['amountIncludeVat'],
        'workflow_id': value['workflowId'],
        'current_step_id': value['currentStepId'],
        'trn_status': APCNstatusToJSON(value['trnStatus']),
    };
}

