/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ARCNstatus } from './ARCNstatus';
import {
    ARCNstatusFromJSON,
    ARCNstatusFromJSONTyped,
    ARCNstatusToJSON,
    ARCNstatusToJSONTyped,
} from './ARCNstatus';

/**
 * 
 * @export
 * @interface ApprovalARCNRebateModel
 */
export interface ApprovalARCNRebateModel {
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNRebateModel
     */
    rowNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNRebateModel
     */
    companyId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNRebateModel
     */
    organizationId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNRebateModel
     */
    ownerUserId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNRebateModel
     */
    rbtCnarBrandId?: number;
    /**
     * 
     * @type {string}
     * @memberof ApprovalARCNRebateModel
     */
    rebateCode?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApprovalARCNRebateModel
     */
    cnDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ApprovalARCNRebateModel
     */
    brandName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalARCNRebateModel
     */
    customerName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApprovalARCNRebateModel
     */
    cnNo?: string;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNRebateModel
     */
    rebateAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNRebateModel
     */
    cnAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNRebateModel
     */
    vat?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNRebateModel
     */
    amountIncludeVat?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNRebateModel
     */
    workflowId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalARCNRebateModel
     */
    currentStepId?: number;
    /**
     * 
     * @type {ARCNstatus}
     * @memberof ApprovalARCNRebateModel
     */
    trnStatus?: ARCNstatus;
}



/**
 * Check if a given object implements the ApprovalARCNRebateModel interface.
 */
export function instanceOfApprovalARCNRebateModel(value: object): value is ApprovalARCNRebateModel {
    return true;
}

export function ApprovalARCNRebateModelFromJSON(json: any): ApprovalARCNRebateModel {
    return ApprovalARCNRebateModelFromJSONTyped(json, false);
}

export function ApprovalARCNRebateModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovalARCNRebateModel {
    if (json == null) {
        return json;
    }
    return {
        
        'rowNumber': json['row_number'] == null ? undefined : json['row_number'],
        'companyId': json['company_id'] == null ? undefined : json['company_id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'ownerUserId': json['owner_user_id'] == null ? undefined : json['owner_user_id'],
        'rbtCnarBrandId': json['rbt_cnar_brand_id'] == null ? undefined : json['rbt_cnar_brand_id'],
        'rebateCode': json['rebate_code'] == null ? undefined : json['rebate_code'],
        'cnDate': json['cn_date'] == null ? undefined : (new Date(json['cn_date'])),
        'brandName': json['brand_name'] == null ? undefined : json['brand_name'],
        'customerName': json['customer_name'] == null ? undefined : json['customer_name'],
        'cnNo': json['cn_no'] == null ? undefined : json['cn_no'],
        'rebateAmount': json['rebate_amount'] == null ? undefined : json['rebate_amount'],
        'cnAmount': json['cn_amount'] == null ? undefined : json['cn_amount'],
        'vat': json['vat'] == null ? undefined : json['vat'],
        'amountIncludeVat': json['amount_include_vat'] == null ? undefined : json['amount_include_vat'],
        'workflowId': json['workflow_id'] == null ? undefined : json['workflow_id'],
        'currentStepId': json['current_step_id'] == null ? undefined : json['current_step_id'],
        'trnStatus': json['trn_status'] == null ? undefined : ARCNstatusFromJSON(json['trn_status']),
    };
}

export function ApprovalARCNRebateModelToJSON(json: any): ApprovalARCNRebateModel {
    return ApprovalARCNRebateModelToJSONTyped(json, false);
}

export function ApprovalARCNRebateModelToJSONTyped(value?: ApprovalARCNRebateModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row_number': value['rowNumber'],
        'company_id': value['companyId'],
        'organization_id': value['organizationId'],
        'owner_user_id': value['ownerUserId'],
        'rbt_cnar_brand_id': value['rbtCnarBrandId'],
        'rebate_code': value['rebateCode'],
        'cn_date': value['cnDate'] == null ? undefined : ((value['cnDate']).toISOString()),
        'brand_name': value['brandName'],
        'customer_name': value['customerName'],
        'cn_no': value['cnNo'],
        'rebate_amount': value['rebateAmount'],
        'cn_amount': value['cnAmount'],
        'vat': value['vat'],
        'amount_include_vat': value['amountIncludeVat'],
        'workflow_id': value['workflowId'],
        'current_step_id': value['currentStepId'],
        'trn_status': ARCNstatusToJSON(value['trnStatus']),
    };
}

