/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ARCNInHouseCustomerDetail
 */
export interface ARCNInHouseCustomerDetail {
    /**
     * 
     * @type {string}
     * @memberof ARCNInHouseCustomerDetail
     */
    rebateCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ARCNInHouseCustomerDetail
     */
    taxPayerId?: string;
    /**
     * 
     * @type {string}
     * @memberof ARCNInHouseCustomerDetail
     */
    revenueBranchCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ARCNInHouseCustomerDetail
     */
    customerName?: string;
    /**
     * 
     * @type {string}
     * @memberof ARCNInHouseCustomerDetail
     */
    fullAddress?: string;
    /**
     * 
     * @type {number}
     * @memberof ARCNInHouseCustomerDetail
     */
    provinceId?: number;
    /**
     * 
     * @type {number}
     * @memberof ARCNInHouseCustomerDetail
     */
    districtId?: number;
    /**
     * 
     * @type {number}
     * @memberof ARCNInHouseCustomerDetail
     */
    subDistrictId?: number;
    /**
     * 
     * @type {string}
     * @memberof ARCNInHouseCustomerDetail
     */
    zipCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ARCNInHouseCustomerDetail
     */
    telephone?: string;
    /**
     * 
     * @type {string}
     * @memberof ARCNInHouseCustomerDetail
     */
    email?: string;
}

/**
 * Check if a given object implements the ARCNInHouseCustomerDetail interface.
 */
export function instanceOfARCNInHouseCustomerDetail(value: object): value is ARCNInHouseCustomerDetail {
    return true;
}

export function ARCNInHouseCustomerDetailFromJSON(json: any): ARCNInHouseCustomerDetail {
    return ARCNInHouseCustomerDetailFromJSONTyped(json, false);
}

export function ARCNInHouseCustomerDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ARCNInHouseCustomerDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'rebateCode': json['rebate_code'] == null ? undefined : json['rebate_code'],
        'taxPayerId': json['tax_payer_id'] == null ? undefined : json['tax_payer_id'],
        'revenueBranchCode': json['revenue_branch_code'] == null ? undefined : json['revenue_branch_code'],
        'customerName': json['customer_name'] == null ? undefined : json['customer_name'],
        'fullAddress': json['full_address'] == null ? undefined : json['full_address'],
        'provinceId': json['province_id'] == null ? undefined : json['province_id'],
        'districtId': json['district_id'] == null ? undefined : json['district_id'],
        'subDistrictId': json['sub_district_id'] == null ? undefined : json['sub_district_id'],
        'zipCode': json['zip_code'] == null ? undefined : json['zip_code'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function ARCNInHouseCustomerDetailToJSON(json: any): ARCNInHouseCustomerDetail {
    return ARCNInHouseCustomerDetailToJSONTyped(json, false);
}

export function ARCNInHouseCustomerDetailToJSONTyped(value?: ARCNInHouseCustomerDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rebate_code': value['rebateCode'],
        'tax_payer_id': value['taxPayerId'],
        'revenue_branch_code': value['revenueBranchCode'],
        'customer_name': value['customerName'],
        'full_address': value['fullAddress'],
        'province_id': value['provinceId'],
        'district_id': value['districtId'],
        'sub_district_id': value['subDistrictId'],
        'zip_code': value['zipCode'],
        'telephone': value['telephone'],
        'email': value['email'],
    };
}

