/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingPlanPatchModel
 */
export interface BillingPlanPatchModel {
    /**
     * 
     * @type {number}
     * @memberof BillingPlanPatchModel
     */
    billingPlanId?: number;
    /**
     * 
     * @type {number}
     * @memberof BillingPlanPatchModel
     */
    planAmount?: number;
    /**
     * 
     * @type {Date}
     * @memberof BillingPlanPatchModel
     */
    planDate?: Date;
}

/**
 * Check if a given object implements the BillingPlanPatchModel interface.
 */
export function instanceOfBillingPlanPatchModel(value: object): value is BillingPlanPatchModel {
    return true;
}

export function BillingPlanPatchModelFromJSON(json: any): BillingPlanPatchModel {
    return BillingPlanPatchModelFromJSONTyped(json, false);
}

export function BillingPlanPatchModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingPlanPatchModel {
    if (json == null) {
        return json;
    }
    return {
        
        'billingPlanId': json['billing_plan_id'] == null ? undefined : json['billing_plan_id'],
        'planAmount': json['plan_amount'] == null ? undefined : json['plan_amount'],
        'planDate': json['plan_date'] == null ? undefined : (new Date(json['plan_date'])),
    };
}

export function BillingPlanPatchModelToJSON(json: any): BillingPlanPatchModel {
    return BillingPlanPatchModelToJSONTyped(json, false);
}

export function BillingPlanPatchModelToJSONTyped(value?: BillingPlanPatchModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'billing_plan_id': value['billingPlanId'],
        'plan_amount': value['planAmount'],
        'plan_date': value['planDate'] == null ? undefined : ((value['planDate']).toISOString()),
    };
}

