/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingPlanModel
 */
export interface BillingPlanModel {
    /**
     * 
     * @type {number}
     * @memberof BillingPlanModel
     */
    billingPlanId?: number;
    /**
     * 
     * @type {string}
     * @memberof BillingPlanModel
     */
    customerName?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingPlanModel
     */
    invoiceNo?: string;
    /**
     * 
     * @type {Date}
     * @memberof BillingPlanModel
     */
    invoiceDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof BillingPlanModel
     */
    soNo?: string;
    /**
     * 
     * @type {Date}
     * @memberof BillingPlanModel
     */
    soDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof BillingPlanModel
     */
    invoiceAmount?: number;
    /**
     * 
     * @type {Date}
     * @memberof BillingPlanModel
     */
    paymentDue?: Date;
    /**
     * 
     * @type {number}
     * @memberof BillingPlanModel
     */
    overDue?: number;
    /**
     * 
     * @type {number}
     * @memberof BillingPlanModel
     */
    aging?: number;
    /**
     * 
     * @type {number}
     * @memberof BillingPlanModel
     */
    planAmountArgo?: number;
    /**
     * 
     * @type {Date}
     * @memberof BillingPlanModel
     */
    planDateArgo?: Date;
    /**
     * 
     * @type {number}
     * @memberof BillingPlanModel
     */
    planAmount?: number;
    /**
     * 
     * @type {Date}
     * @memberof BillingPlanModel
     */
    planDate?: Date;
}

/**
 * Check if a given object implements the BillingPlanModel interface.
 */
export function instanceOfBillingPlanModel(value: object): value is BillingPlanModel {
    return true;
}

export function BillingPlanModelFromJSON(json: any): BillingPlanModel {
    return BillingPlanModelFromJSONTyped(json, false);
}

export function BillingPlanModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingPlanModel {
    if (json == null) {
        return json;
    }
    return {
        
        'billingPlanId': json['billing_plan_id'] == null ? undefined : json['billing_plan_id'],
        'customerName': json['customer_name'] == null ? undefined : json['customer_name'],
        'invoiceNo': json['invoice_no'] == null ? undefined : json['invoice_no'],
        'invoiceDate': json['invoice_date'] == null ? undefined : (new Date(json['invoice_date'])),
        'soNo': json['so_no'] == null ? undefined : json['so_no'],
        'soDate': json['so_date'] == null ? undefined : (new Date(json['so_date'])),
        'invoiceAmount': json['invoice_amount'] == null ? undefined : json['invoice_amount'],
        'paymentDue': json['payment_due'] == null ? undefined : (new Date(json['payment_due'])),
        'overDue': json['over_due'] == null ? undefined : json['over_due'],
        'aging': json['aging'] == null ? undefined : json['aging'],
        'planAmountArgo': json['plan_amount_argo'] == null ? undefined : json['plan_amount_argo'],
        'planDateArgo': json['plan_date_argo'] == null ? undefined : (new Date(json['plan_date_argo'])),
        'planAmount': json['plan_amount'] == null ? undefined : json['plan_amount'],
        'planDate': json['plan_date'] == null ? undefined : (new Date(json['plan_date'])),
    };
}

export function BillingPlanModelToJSON(json: any): BillingPlanModel {
    return BillingPlanModelToJSONTyped(json, false);
}

export function BillingPlanModelToJSONTyped(value?: BillingPlanModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'billing_plan_id': value['billingPlanId'],
        'customer_name': value['customerName'],
        'invoice_no': value['invoiceNo'],
        'invoice_date': value['invoiceDate'] == null ? undefined : ((value['invoiceDate']).toISOString()),
        'so_no': value['soNo'],
        'so_date': value['soDate'] == null ? undefined : ((value['soDate']).toISOString()),
        'invoice_amount': value['invoiceAmount'],
        'payment_due': value['paymentDue'] == null ? undefined : ((value['paymentDue']).toISOString()),
        'over_due': value['overDue'],
        'aging': value['aging'],
        'plan_amount_argo': value['planAmountArgo'],
        'plan_date_argo': value['planDateArgo'] == null ? undefined : ((value['planDateArgo']).toISOString()),
        'plan_amount': value['planAmount'],
        'plan_date': value['planDate'] == null ? undefined : ((value['planDate']).toISOString()),
    };
}

