/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimCNJobModel
 */
export interface ClaimCNJobModel {
    /**
     * 
     * @type {number}
     * @memberof ClaimCNJobModel
     */
    rowNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    serviceDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    tagbarCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    jobClaimNo?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    cnNo?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    cnDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    invoiceNo?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    brandsDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    productID?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    productDescription?: string;
    /**
     * 
     * @type {number}
     * @memberof ClaimCNJobModel
     */
    warrantyMonth?: number;
    /**
     * 
     * @type {number}
     * @memberof ClaimCNJobModel
     */
    warrantyLeft?: number;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    snCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    saleCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    saleName?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    shopCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    shopName?: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    cnCreateRemark?: string;
    /**
     * 
     * @type {number}
     * @memberof ClaimCNJobModel
     */
    cnCreatePriorityType?: number;
    /**
     * 
     * @type {number}
     * @memberof ClaimCNJobModel
     */
    cnCreateType?: number;
    /**
     * 
     * @type {number}
     * @memberof ClaimCNJobModel
     */
    cnPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ClaimCNJobModel
     */
    cnRestorePercent?: number;
    /**
     * 
     * @type {number}
     * @memberof ClaimCNJobModel
     */
    cnRestoreAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof ClaimCNJobModel
     */
    cnClaimType?: string;
}

/**
 * Check if a given object implements the ClaimCNJobModel interface.
 */
export function instanceOfClaimCNJobModel(value: object): value is ClaimCNJobModel {
    return true;
}

export function ClaimCNJobModelFromJSON(json: any): ClaimCNJobModel {
    return ClaimCNJobModelFromJSONTyped(json, false);
}

export function ClaimCNJobModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimCNJobModel {
    if (json == null) {
        return json;
    }
    return {
        
        'rowNumber': json['rowNumber'] == null ? undefined : json['rowNumber'],
        'serviceDate': json['serviceDate'] == null ? undefined : json['serviceDate'],
        'tagbarCode': json['tagbarCode'] == null ? undefined : json['tagbarCode'],
        'jobClaimNo': json['jobClaimNo'] == null ? undefined : json['jobClaimNo'],
        'cnNo': json['cnNo'] == null ? undefined : json['cnNo'],
        'cnDate': json['cnDate'] == null ? undefined : json['cnDate'],
        'invoiceNo': json['invoiceNo'] == null ? undefined : json['invoiceNo'],
        'brandsDescription': json['brandsDescription'] == null ? undefined : json['brandsDescription'],
        'productID': json['productID'] == null ? undefined : json['productID'],
        'productDescription': json['productDescription'] == null ? undefined : json['productDescription'],
        'warrantyMonth': json['warrantyMonth'] == null ? undefined : json['warrantyMonth'],
        'warrantyLeft': json['warrantyLeft'] == null ? undefined : json['warrantyLeft'],
        'snCode': json['snCode'] == null ? undefined : json['snCode'],
        'saleCode': json['saleCode'] == null ? undefined : json['saleCode'],
        'saleName': json['saleName'] == null ? undefined : json['saleName'],
        'shopCode': json['shopCode'] == null ? undefined : json['shopCode'],
        'shopName': json['shopName'] == null ? undefined : json['shopName'],
        'cnCreateRemark': json['cnCreateRemark'] == null ? undefined : json['cnCreateRemark'],
        'cnCreatePriorityType': json['cnCreatePriorityType'] == null ? undefined : json['cnCreatePriorityType'],
        'cnCreateType': json['cnCreateType'] == null ? undefined : json['cnCreateType'],
        'cnPrice': json['cnPrice'] == null ? undefined : json['cnPrice'],
        'cnRestorePercent': json['cnRestorePercent'] == null ? undefined : json['cnRestorePercent'],
        'cnRestoreAmount': json['cnRestoreAmount'] == null ? undefined : json['cnRestoreAmount'],
        'cnClaimType': json['cnClaimType'] == null ? undefined : json['cnClaimType'],
    };
}

export function ClaimCNJobModelToJSON(json: any): ClaimCNJobModel {
    return ClaimCNJobModelToJSONTyped(json, false);
}

export function ClaimCNJobModelToJSONTyped(value?: ClaimCNJobModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rowNumber': value['rowNumber'],
        'serviceDate': value['serviceDate'],
        'tagbarCode': value['tagbarCode'],
        'jobClaimNo': value['jobClaimNo'],
        'cnNo': value['cnNo'],
        'cnDate': value['cnDate'],
        'invoiceNo': value['invoiceNo'],
        'brandsDescription': value['brandsDescription'],
        'productID': value['productID'],
        'productDescription': value['productDescription'],
        'warrantyMonth': value['warrantyMonth'],
        'warrantyLeft': value['warrantyLeft'],
        'snCode': value['snCode'],
        'saleCode': value['saleCode'],
        'saleName': value['saleName'],
        'shopCode': value['shopCode'],
        'shopName': value['shopName'],
        'cnCreateRemark': value['cnCreateRemark'],
        'cnCreatePriorityType': value['cnCreatePriorityType'],
        'cnCreateType': value['cnCreateType'],
        'cnPrice': value['cnPrice'],
        'cnRestorePercent': value['cnRestorePercent'],
        'cnRestoreAmount': value['cnRestoreAmount'],
        'cnClaimType': value['cnClaimType'],
    };
}

