/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigModel } from './ConfigModel';
import {
    ConfigModelFromJSON,
    ConfigModelFromJSONTyped,
    ConfigModelToJSON,
    ConfigModelToJSONTyped,
} from './ConfigModel';

/**
 * 
 * @export
 * @interface ConfigModelBaseResponsePagination
 */
export interface ConfigModelBaseResponsePagination {
    /**
     * 
     * @type {boolean}
     * @memberof ConfigModelBaseResponsePagination
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigModelBaseResponsePagination
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigModelBaseResponsePagination
     */
    statusCode?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigModelBaseResponsePagination
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigModelBaseResponsePagination
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigModelBaseResponsePagination
     */
    pageAll?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigModelBaseResponsePagination
     */
    totalRecord?: number;
    /**
     * 
     * @type {Array<ConfigModel>}
     * @memberof ConfigModelBaseResponsePagination
     */
    data?: Array<ConfigModel>;
}

/**
 * Check if a given object implements the ConfigModelBaseResponsePagination interface.
 */
export function instanceOfConfigModelBaseResponsePagination(value: object): value is ConfigModelBaseResponsePagination {
    return true;
}

export function ConfigModelBaseResponsePaginationFromJSON(json: any): ConfigModelBaseResponsePagination {
    return ConfigModelBaseResponsePaginationFromJSONTyped(json, false);
}

export function ConfigModelBaseResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigModelBaseResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'pageIndex': json['pageIndex'] == null ? undefined : json['pageIndex'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageAll': json['pageAll'] == null ? undefined : json['pageAll'],
        'totalRecord': json['totalRecord'] == null ? undefined : json['totalRecord'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ConfigModelFromJSON)),
    };
}

export function ConfigModelBaseResponsePaginationToJSON(json: any): ConfigModelBaseResponsePagination {
    return ConfigModelBaseResponsePaginationToJSONTyped(json, false);
}

export function ConfigModelBaseResponsePaginationToJSONTyped(value?: ConfigModelBaseResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'pageIndex': value['pageIndex'],
        'pageSize': value['pageSize'],
        'pageAll': value['pageAll'],
        'totalRecord': value['totalRecord'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ConfigModelToJSON)),
    };
}

