/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigDetailModel } from './ConfigDetailModel';
import {
    ConfigDetailModelFromJSON,
    ConfigDetailModelFromJSONTyped,
    ConfigDetailModelToJSON,
    ConfigDetailModelToJSONTyped,
} from './ConfigDetailModel';

/**
 * 
 * @export
 * @interface ConfigDetailModelBaseResponseModel
 */
export interface ConfigDetailModelBaseResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof ConfigDetailModelBaseResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigDetailModelBaseResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigDetailModelBaseResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {ConfigDetailModel}
     * @memberof ConfigDetailModelBaseResponseModel
     */
    data?: ConfigDetailModel;
}

/**
 * Check if a given object implements the ConfigDetailModelBaseResponseModel interface.
 */
export function instanceOfConfigDetailModelBaseResponseModel(value: object): value is ConfigDetailModelBaseResponseModel {
    return true;
}

export function ConfigDetailModelBaseResponseModelFromJSON(json: any): ConfigDetailModelBaseResponseModel {
    return ConfigDetailModelBaseResponseModelFromJSONTyped(json, false);
}

export function ConfigDetailModelBaseResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigDetailModelBaseResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'data': json['data'] == null ? undefined : ConfigDetailModelFromJSON(json['data']),
    };
}

export function ConfigDetailModelBaseResponseModelToJSON(json: any): ConfigDetailModelBaseResponseModel {
    return ConfigDetailModelBaseResponseModelToJSONTyped(json, false);
}

export function ConfigDetailModelBaseResponseModelToJSONTyped(value?: ConfigDetailModelBaseResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'data': ConfigDetailModelToJSON(value['data']),
    };
}

