/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditworthinessModel
 */
export interface CreditworthinessModel {
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    fsClass?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    fsClassScore?: number;
    /**
     * 
     * @type {string}
     * @memberof CreditworthinessModel
     */
    fsGrade?: string;
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    fsGradeScore?: number;
    /**
     * 
     * @type {string}
     * @memberof CreditworthinessModel
     */
    director?: string;
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    directorScore?: number;
    /**
     * 
     * @type {string}
     * @memberof CreditworthinessModel
     */
    shareholder?: string;
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    shareholderScore?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    creditLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    creditLimitScore?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    creditTerm?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    creditTermScore?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    maxscoreG2?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    actualScoreG2?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    percentG2?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditworthinessModel
     */
    percentWeightG2?: number;
}

/**
 * Check if a given object implements the CreditworthinessModel interface.
 */
export function instanceOfCreditworthinessModel(value: object): value is CreditworthinessModel {
    return true;
}

export function CreditworthinessModelFromJSON(json: any): CreditworthinessModel {
    return CreditworthinessModelFromJSONTyped(json, false);
}

export function CreditworthinessModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditworthinessModel {
    if (json == null) {
        return json;
    }
    return {
        
        'fsClass': json['fs_class'] == null ? undefined : json['fs_class'],
        'fsClassScore': json['fs_class_score'] == null ? undefined : json['fs_class_score'],
        'fsGrade': json['fs_grade'] == null ? undefined : json['fs_grade'],
        'fsGradeScore': json['fs_grade_score'] == null ? undefined : json['fs_grade_score'],
        'director': json['director'] == null ? undefined : json['director'],
        'directorScore': json['director_score'] == null ? undefined : json['director_score'],
        'shareholder': json['shareholder'] == null ? undefined : json['shareholder'],
        'shareholderScore': json['shareholder_score'] == null ? undefined : json['shareholder_score'],
        'creditLimit': json['credit_limit'] == null ? undefined : json['credit_limit'],
        'creditLimitScore': json['credit_limit_score'] == null ? undefined : json['credit_limit_score'],
        'creditTerm': json['credit_term'] == null ? undefined : json['credit_term'],
        'creditTermScore': json['credit_term_score'] == null ? undefined : json['credit_term_score'],
        'maxscoreG2': json['maxscore_g2'] == null ? undefined : json['maxscore_g2'],
        'actualScoreG2': json['actual_score_g2'] == null ? undefined : json['actual_score_g2'],
        'percentG2': json['percent_g2'] == null ? undefined : json['percent_g2'],
        'percentWeightG2': json['percent_weight_g2'] == null ? undefined : json['percent_weight_g2'],
    };
}

export function CreditworthinessModelToJSON(json: any): CreditworthinessModel {
    return CreditworthinessModelToJSONTyped(json, false);
}

export function CreditworthinessModelToJSONTyped(value?: CreditworthinessModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fs_class': value['fsClass'],
        'fs_class_score': value['fsClassScore'],
        'fs_grade': value['fsGrade'],
        'fs_grade_score': value['fsGradeScore'],
        'director': value['director'],
        'director_score': value['directorScore'],
        'shareholder': value['shareholder'],
        'shareholder_score': value['shareholderScore'],
        'credit_limit': value['creditLimit'],
        'credit_limit_score': value['creditLimitScore'],
        'credit_term': value['creditTerm'],
        'credit_term_score': value['creditTermScore'],
        'maxscore_g2': value['maxscoreG2'],
        'actual_score_g2': value['actualScoreG2'],
        'percent_g2': value['percentG2'],
        'percent_weight_g2': value['percentWeightG2'],
    };
}

