/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDetailModel } from './UserDetailModel';
import {
    UserDetailModelFromJSON,
    UserDetailModelFromJSONTyped,
    UserDetailModelToJSON,
    UserDetailModelToJSONTyped,
} from './UserDetailModel';
import type { TokenModel } from './TokenModel';
import {
    TokenModelFromJSON,
    TokenModelFromJSONTyped,
    TokenModelToJSON,
    TokenModelToJSONTyped,
} from './TokenModel';

/**
 * 
 * @export
 * @interface CustomerVerifyTokenResponseModel
 */
export interface CustomerVerifyTokenResponseModel {
    /**
     * 
     * @type {TokenModel}
     * @memberof CustomerVerifyTokenResponseModel
     */
    tokenResponse?: TokenModel;
    /**
     * 
     * @type {UserDetailModel}
     * @memberof CustomerVerifyTokenResponseModel
     */
    userDetailResponse?: UserDetailModel;
}

/**
 * Check if a given object implements the CustomerVerifyTokenResponseModel interface.
 */
export function instanceOfCustomerVerifyTokenResponseModel(value: object): value is CustomerVerifyTokenResponseModel {
    return true;
}

export function CustomerVerifyTokenResponseModelFromJSON(json: any): CustomerVerifyTokenResponseModel {
    return CustomerVerifyTokenResponseModelFromJSONTyped(json, false);
}

export function CustomerVerifyTokenResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerVerifyTokenResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'tokenResponse': json['tokenResponse'] == null ? undefined : TokenModelFromJSON(json['tokenResponse']),
        'userDetailResponse': json['userDetailResponse'] == null ? undefined : UserDetailModelFromJSON(json['userDetailResponse']),
    };
}

export function CustomerVerifyTokenResponseModelToJSON(json: any): CustomerVerifyTokenResponseModel {
    return CustomerVerifyTokenResponseModelToJSONTyped(json, false);
}

export function CustomerVerifyTokenResponseModelToJSONTyped(value?: CustomerVerifyTokenResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tokenResponse': TokenModelToJSON(value['tokenResponse']),
        'userDetailResponse': UserDetailModelToJSON(value['userDetailResponse']),
    };
}

