/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DebtLetterInvoiceGetSearchModel } from './DebtLetterInvoiceGetSearchModel';
import {
    DebtLetterInvoiceGetSearchModelFromJSON,
    DebtLetterInvoiceGetSearchModelFromJSONTyped,
    DebtLetterInvoiceGetSearchModelToJSON,
    DebtLetterInvoiceGetSearchModelToJSONTyped,
} from './DebtLetterInvoiceGetSearchModel';

/**
 * 
 * @export
 * @interface DebtLetterInvoiceGetSearchModelBaseResponsePagination
 */
export interface DebtLetterInvoiceGetSearchModelBaseResponsePagination {
    /**
     * 
     * @type {boolean}
     * @memberof DebtLetterInvoiceGetSearchModelBaseResponsePagination
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DebtLetterInvoiceGetSearchModelBaseResponsePagination
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof DebtLetterInvoiceGetSearchModelBaseResponsePagination
     */
    statusCode?: number;
    /**
     * 
     * @type {number}
     * @memberof DebtLetterInvoiceGetSearchModelBaseResponsePagination
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof DebtLetterInvoiceGetSearchModelBaseResponsePagination
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof DebtLetterInvoiceGetSearchModelBaseResponsePagination
     */
    pageAll?: number;
    /**
     * 
     * @type {number}
     * @memberof DebtLetterInvoiceGetSearchModelBaseResponsePagination
     */
    totalRecord?: number;
    /**
     * 
     * @type {Array<DebtLetterInvoiceGetSearchModel>}
     * @memberof DebtLetterInvoiceGetSearchModelBaseResponsePagination
     */
    data?: Array<DebtLetterInvoiceGetSearchModel>;
}

/**
 * Check if a given object implements the DebtLetterInvoiceGetSearchModelBaseResponsePagination interface.
 */
export function instanceOfDebtLetterInvoiceGetSearchModelBaseResponsePagination(value: object): value is DebtLetterInvoiceGetSearchModelBaseResponsePagination {
    return true;
}

export function DebtLetterInvoiceGetSearchModelBaseResponsePaginationFromJSON(json: any): DebtLetterInvoiceGetSearchModelBaseResponsePagination {
    return DebtLetterInvoiceGetSearchModelBaseResponsePaginationFromJSONTyped(json, false);
}

export function DebtLetterInvoiceGetSearchModelBaseResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebtLetterInvoiceGetSearchModelBaseResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'pageIndex': json['pageIndex'] == null ? undefined : json['pageIndex'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageAll': json['pageAll'] == null ? undefined : json['pageAll'],
        'totalRecord': json['totalRecord'] == null ? undefined : json['totalRecord'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DebtLetterInvoiceGetSearchModelFromJSON)),
    };
}

export function DebtLetterInvoiceGetSearchModelBaseResponsePaginationToJSON(json: any): DebtLetterInvoiceGetSearchModelBaseResponsePagination {
    return DebtLetterInvoiceGetSearchModelBaseResponsePaginationToJSONTyped(json, false);
}

export function DebtLetterInvoiceGetSearchModelBaseResponsePaginationToJSONTyped(value?: DebtLetterInvoiceGetSearchModelBaseResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'pageIndex': value['pageIndex'],
        'pageSize': value['pageSize'],
        'pageAll': value['pageAll'],
        'totalRecord': value['totalRecord'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DebtLetterInvoiceGetSearchModelToJSON)),
    };
}

