/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DebtLetterBookInvoiceInterfaceListModel } from './DebtLetterBookInvoiceInterfaceListModel';
import {
    DebtLetterBookInvoiceInterfaceListModelFromJSON,
    DebtLetterBookInvoiceInterfaceListModelFromJSONTyped,
    DebtLetterBookInvoiceInterfaceListModelToJSON,
    DebtLetterBookInvoiceInterfaceListModelToJSONTyped,
} from './DebtLetterBookInvoiceInterfaceListModel';

/**
 * 
 * @export
 * @interface DebtLetterBookInvoiceInterfaceModel
 */
export interface DebtLetterBookInvoiceInterfaceModel {
    /**
     * 
     * @type {number}
     * @memberof DebtLetterBookInvoiceInterfaceModel
     */
    bookId?: number;
    /**
     * 
     * @type {Array<DebtLetterBookInvoiceInterfaceListModel>}
     * @memberof DebtLetterBookInvoiceInterfaceModel
     */
    invoiceList?: Array<DebtLetterBookInvoiceInterfaceListModel>;
}

/**
 * Check if a given object implements the DebtLetterBookInvoiceInterfaceModel interface.
 */
export function instanceOfDebtLetterBookInvoiceInterfaceModel(value: object): value is DebtLetterBookInvoiceInterfaceModel {
    return true;
}

export function DebtLetterBookInvoiceInterfaceModelFromJSON(json: any): DebtLetterBookInvoiceInterfaceModel {
    return DebtLetterBookInvoiceInterfaceModelFromJSONTyped(json, false);
}

export function DebtLetterBookInvoiceInterfaceModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebtLetterBookInvoiceInterfaceModel {
    if (json == null) {
        return json;
    }
    return {
        
        'bookId': json['book_id'] == null ? undefined : json['book_id'],
        'invoiceList': json['invoice_list'] == null ? undefined : ((json['invoice_list'] as Array<any>).map(DebtLetterBookInvoiceInterfaceListModelFromJSON)),
    };
}

export function DebtLetterBookInvoiceInterfaceModelToJSON(json: any): DebtLetterBookInvoiceInterfaceModel {
    return DebtLetterBookInvoiceInterfaceModelToJSONTyped(json, false);
}

export function DebtLetterBookInvoiceInterfaceModelToJSONTyped(value?: DebtLetterBookInvoiceInterfaceModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'book_id': value['bookId'],
        'invoice_list': value['invoiceList'] == null ? undefined : ((value['invoiceList'] as Array<any>).map(DebtLetterBookInvoiceInterfaceListModelToJSON)),
    };
}

