/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DropdownModel } from './DropdownModel';
import {
    DropdownModelFromJSON,
    DropdownModelFromJSONTyped,
    DropdownModelToJSON,
    DropdownModelToJSONTyped,
} from './DropdownModel';

/**
 * 
 * @export
 * @interface DropdownModelListBaseResponseModel
 */
export interface DropdownModelListBaseResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof DropdownModelListBaseResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DropdownModelListBaseResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof DropdownModelListBaseResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {Array<DropdownModel>}
     * @memberof DropdownModelListBaseResponseModel
     */
    data?: Array<DropdownModel>;
}

/**
 * Check if a given object implements the DropdownModelListBaseResponseModel interface.
 */
export function instanceOfDropdownModelListBaseResponseModel(value: object): value is DropdownModelListBaseResponseModel {
    return true;
}

export function DropdownModelListBaseResponseModelFromJSON(json: any): DropdownModelListBaseResponseModel {
    return DropdownModelListBaseResponseModelFromJSONTyped(json, false);
}

export function DropdownModelListBaseResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DropdownModelListBaseResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DropdownModelFromJSON)),
    };
}

export function DropdownModelListBaseResponseModelToJSON(json: any): DropdownModelListBaseResponseModel {
    return DropdownModelListBaseResponseModelToJSONTyped(json, false);
}

export function DropdownModelListBaseResponseModelToJSONTyped(value?: DropdownModelListBaseResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DropdownModelToJSON)),
    };
}

