/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DropdownModel
 */
export interface DropdownModel {
    /**
     * 
     * @type {number}
     * @memberof DropdownModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DropdownModel
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof DropdownModel
     */
    value?: string;
}

/**
 * Check if a given object implements the DropdownModel interface.
 */
export function instanceOfDropdownModel(value: object): value is DropdownModel {
    return true;
}

export function DropdownModelFromJSON(json: any): DropdownModel {
    return DropdownModelFromJSONTyped(json, false);
}

export function DropdownModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DropdownModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function DropdownModelToJSON(json: any): DropdownModel {
    return DropdownModelToJSONTyped(json, false);
}

export function DropdownModelToJSONTyped(value?: DropdownModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'value': value['value'],
    };
}

