/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DropdownEmployeeModel
 */
export interface DropdownEmployeeModel {
    /**
     * 
     * @type {number}
     * @memberof DropdownEmployeeModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DropdownEmployeeModel
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof DropdownEmployeeModel
     */
    value?: string;
    /**
     * 
     * @type {number}
     * @memberof DropdownEmployeeModel
     */
    rowNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof DropdownEmployeeModel
     */
    employeeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof DropdownEmployeeModel
     */
    firstnameTh?: string;
    /**
     * 
     * @type {string}
     * @memberof DropdownEmployeeModel
     */
    lastnameTh?: string;
    /**
     * 
     * @type {string}
     * @memberof DropdownEmployeeModel
     */
    firstnameEn?: string;
    /**
     * 
     * @type {string}
     * @memberof DropdownEmployeeModel
     */
    lastnameEn?: string;
    /**
     * 
     * @type {number}
     * @memberof DropdownEmployeeModel
     */
    organizationId?: number;
}

/**
 * Check if a given object implements the DropdownEmployeeModel interface.
 */
export function instanceOfDropdownEmployeeModel(value: object): value is DropdownEmployeeModel {
    return true;
}

export function DropdownEmployeeModelFromJSON(json: any): DropdownEmployeeModel {
    return DropdownEmployeeModelFromJSONTyped(json, false);
}

export function DropdownEmployeeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DropdownEmployeeModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
        'rowNumber': json['row_number'] == null ? undefined : json['row_number'],
        'employeeCode': json['employee_code'] == null ? undefined : json['employee_code'],
        'firstnameTh': json['firstname_th'] == null ? undefined : json['firstname_th'],
        'lastnameTh': json['lastname_th'] == null ? undefined : json['lastname_th'],
        'firstnameEn': json['firstname_en'] == null ? undefined : json['firstname_en'],
        'lastnameEn': json['lastname_en'] == null ? undefined : json['lastname_en'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
    };
}

export function DropdownEmployeeModelToJSON(json: any): DropdownEmployeeModel {
    return DropdownEmployeeModelToJSONTyped(json, false);
}

export function DropdownEmployeeModelToJSONTyped(value?: DropdownEmployeeModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'value': value['value'],
        'row_number': value['rowNumber'],
        'employee_code': value['employeeCode'],
        'firstname_th': value['firstnameTh'],
        'lastname_th': value['lastnameTh'],
        'firstname_en': value['firstnameEn'],
        'lastname_en': value['lastnameEn'],
        'organization_id': value['organizationId'],
    };
}

