/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DropdownSubDistrictModel } from './DropdownSubDistrictModel';
import {
    DropdownSubDistrictModelFromJSON,
    DropdownSubDistrictModelFromJSONTyped,
    DropdownSubDistrictModelToJSON,
    DropdownSubDistrictModelToJSONTyped,
} from './DropdownSubDistrictModel';

/**
 * 
 * @export
 * @interface DropdownSubDistrictModelListBaseResponseModel
 */
export interface DropdownSubDistrictModelListBaseResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof DropdownSubDistrictModelListBaseResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DropdownSubDistrictModelListBaseResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof DropdownSubDistrictModelListBaseResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {Array<DropdownSubDistrictModel>}
     * @memberof DropdownSubDistrictModelListBaseResponseModel
     */
    data?: Array<DropdownSubDistrictModel>;
}

/**
 * Check if a given object implements the DropdownSubDistrictModelListBaseResponseModel interface.
 */
export function instanceOfDropdownSubDistrictModelListBaseResponseModel(value: object): value is DropdownSubDistrictModelListBaseResponseModel {
    return true;
}

export function DropdownSubDistrictModelListBaseResponseModelFromJSON(json: any): DropdownSubDistrictModelListBaseResponseModel {
    return DropdownSubDistrictModelListBaseResponseModelFromJSONTyped(json, false);
}

export function DropdownSubDistrictModelListBaseResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DropdownSubDistrictModelListBaseResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DropdownSubDistrictModelFromJSON)),
    };
}

export function DropdownSubDistrictModelListBaseResponseModelToJSON(json: any): DropdownSubDistrictModelListBaseResponseModel {
    return DropdownSubDistrictModelListBaseResponseModelToJSONTyped(json, false);
}

export function DropdownSubDistrictModelListBaseResponseModelToJSONTyped(value?: DropdownSubDistrictModelListBaseResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DropdownSubDistrictModelToJSON)),
    };
}

