/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmployeeOwnerModel
 */
export interface EmployeeOwnerModel {
    /**
     * 
     * @type {number}
     * @memberof EmployeeOwnerModel
     */
    employeeId?: number;
}

/**
 * Check if a given object implements the EmployeeOwnerModel interface.
 */
export function instanceOfEmployeeOwnerModel(value: object): value is EmployeeOwnerModel {
    return true;
}

export function EmployeeOwnerModelFromJSON(json: any): EmployeeOwnerModel {
    return EmployeeOwnerModelFromJSONTyped(json, false);
}

export function EmployeeOwnerModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeOwnerModel {
    if (json == null) {
        return json;
    }
    return {
        
        'employeeId': json['employee_id'] == null ? undefined : json['employee_id'],
    };
}

export function EmployeeOwnerModelToJSON(json: any): EmployeeOwnerModel {
    return EmployeeOwnerModelToJSONTyped(json, false);
}

export function EmployeeOwnerModelToJSONTyped(value?: EmployeeOwnerModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'employee_id': value['employeeId'],
    };
}

