/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImportStatementModel } from './ImportStatementModel';
import {
    ImportStatementModelFromJSON,
    ImportStatementModelFromJSONTyped,
    ImportStatementModelToJSON,
    ImportStatementModelToJSONTyped,
} from './ImportStatementModel';

/**
 * 
 * @export
 * @interface ImportStatementResponseModel
 */
export interface ImportStatementResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof ImportStatementResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ImportStatementResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ImportStatementResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportStatementResponseModel
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportStatementResponseModel
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportStatementResponseModel
     */
    pageAll?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportStatementResponseModel
     */
    totalRecord?: number;
    /**
     * 
     * @type {Array<ImportStatementModel>}
     * @memberof ImportStatementResponseModel
     */
    data?: Array<ImportStatementModel>;
}

/**
 * Check if a given object implements the ImportStatementResponseModel interface.
 */
export function instanceOfImportStatementResponseModel(value: object): value is ImportStatementResponseModel {
    return true;
}

export function ImportStatementResponseModelFromJSON(json: any): ImportStatementResponseModel {
    return ImportStatementResponseModelFromJSONTyped(json, false);
}

export function ImportStatementResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportStatementResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'pageIndex': json['pageIndex'] == null ? undefined : json['pageIndex'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageAll': json['pageAll'] == null ? undefined : json['pageAll'],
        'totalRecord': json['totalRecord'] == null ? undefined : json['totalRecord'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ImportStatementModelFromJSON)),
    };
}

export function ImportStatementResponseModelToJSON(json: any): ImportStatementResponseModel {
    return ImportStatementResponseModelToJSONTyped(json, false);
}

export function ImportStatementResponseModelToJSONTyped(value?: ImportStatementResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'pageIndex': value['pageIndex'],
        'pageSize': value['pageSize'],
        'pageAll': value['pageAll'],
        'totalRecord': value['totalRecord'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ImportStatementModelToJSON)),
    };
}

