/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Invoice
 */
export interface Invoice {
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    invoiceNo?: string;
    /**
     * 
     * @type {Date}
     * @memberof Invoice
     */
    invoiceDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    poNo?: string;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    wagesCost?: number;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    travelExpenses?: number;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    amountOfMoney?: number;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    amountOfVat?: number;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    amountTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    invoiceFilePath?: string;
}

/**
 * Check if a given object implements the Invoice interface.
 */
export function instanceOfInvoice(value: object): value is Invoice {
    return true;
}

export function InvoiceFromJSON(json: any): Invoice {
    return InvoiceFromJSONTyped(json, false);
}

export function InvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invoice {
    if (json == null) {
        return json;
    }
    return {
        
        'invoiceNo': json['invoiceNo'] == null ? undefined : json['invoiceNo'],
        'invoiceDate': json['invoiceDate'] == null ? undefined : (new Date(json['invoiceDate'])),
        'poNo': json['poNo'] == null ? undefined : json['poNo'],
        'wagesCost': json['wagesCost'] == null ? undefined : json['wagesCost'],
        'travelExpenses': json['travelExpenses'] == null ? undefined : json['travelExpenses'],
        'amountOfMoney': json['amountOfMoney'] == null ? undefined : json['amountOfMoney'],
        'amountOfVat': json['amountOfVat'] == null ? undefined : json['amountOfVat'],
        'amountTotal': json['amountTotal'] == null ? undefined : json['amountTotal'],
        'invoiceFilePath': json['invoiceFilePath'] == null ? undefined : json['invoiceFilePath'],
    };
}

export function InvoiceToJSON(json: any): Invoice {
    return InvoiceToJSONTyped(json, false);
}

export function InvoiceToJSONTyped(value?: Invoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invoiceNo': value['invoiceNo'],
        'invoiceDate': value['invoiceDate'] == null ? undefined : ((value['invoiceDate']).toISOString()),
        'poNo': value['poNo'],
        'wagesCost': value['wagesCost'],
        'travelExpenses': value['travelExpenses'],
        'amountOfMoney': value['amountOfMoney'],
        'amountOfVat': value['amountOfVat'],
        'amountTotal': value['amountTotal'],
        'invoiceFilePath': value['invoiceFilePath'],
    };
}

