/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiquidityModel
 */
export interface LiquidityModel {
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    currentRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    currentRatioScore?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    quickRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    quickRatioScore?: number;
    /**
     * 
     * @type {string}
     * @memberof LiquidityModel
     */
    arturnover?: string;
    /**
     * 
     * @type {string}
     * @memberof LiquidityModel
     */
    apturnover?: string;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    avgpaymentperiod?: number;
    /**
     * 
     * @type {string}
     * @memberof LiquidityModel
     */
    inventoryturnover?: string;
    /**
     * 
     * @type {string}
     * @memberof LiquidityModel
     */
    collectionperiod?: string;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    dayssalesinventory?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    grossprofitmargin?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    netprofitmargin?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    roa?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    roe?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    roeScore?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    debtRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    debtRatioScore?: number;
    /**
     * 
     * @type {string}
     * @memberof LiquidityModel
     */
    debttoequity?: string;
    /**
     * 
     * @type {string}
     * @memberof LiquidityModel
     */
    interestcoverage?: string;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    maxscoreG4?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    actualScoreG4?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    percentG4?: number;
    /**
     * 
     * @type {number}
     * @memberof LiquidityModel
     */
    percentWeightG4?: number;
}

/**
 * Check if a given object implements the LiquidityModel interface.
 */
export function instanceOfLiquidityModel(value: object): value is LiquidityModel {
    return true;
}

export function LiquidityModelFromJSON(json: any): LiquidityModel {
    return LiquidityModelFromJSONTyped(json, false);
}

export function LiquidityModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiquidityModel {
    if (json == null) {
        return json;
    }
    return {
        
        'currentRatio': json['current_ratio'] == null ? undefined : json['current_ratio'],
        'currentRatioScore': json['current_ratio_score'] == null ? undefined : json['current_ratio_score'],
        'quickRatio': json['quick_ratio'] == null ? undefined : json['quick_ratio'],
        'quickRatioScore': json['quick_ratio_score'] == null ? undefined : json['quick_ratio_score'],
        'arturnover': json['arturnover'] == null ? undefined : json['arturnover'],
        'apturnover': json['apturnover'] == null ? undefined : json['apturnover'],
        'avgpaymentperiod': json['avgpaymentperiod'] == null ? undefined : json['avgpaymentperiod'],
        'inventoryturnover': json['inventoryturnover'] == null ? undefined : json['inventoryturnover'],
        'collectionperiod': json['collectionperiod'] == null ? undefined : json['collectionperiod'],
        'dayssalesinventory': json['dayssalesinventory'] == null ? undefined : json['dayssalesinventory'],
        'grossprofitmargin': json['grossprofitmargin'] == null ? undefined : json['grossprofitmargin'],
        'netprofitmargin': json['netprofitmargin'] == null ? undefined : json['netprofitmargin'],
        'roa': json['roa'] == null ? undefined : json['roa'],
        'roe': json['roe'] == null ? undefined : json['roe'],
        'roeScore': json['roe_score'] == null ? undefined : json['roe_score'],
        'debtRatio': json['debt_ratio'] == null ? undefined : json['debt_ratio'],
        'debtRatioScore': json['debt_ratio_score'] == null ? undefined : json['debt_ratio_score'],
        'debttoequity': json['debttoequity'] == null ? undefined : json['debttoequity'],
        'interestcoverage': json['interestcoverage'] == null ? undefined : json['interestcoverage'],
        'maxscoreG4': json['maxscore_g4'] == null ? undefined : json['maxscore_g4'],
        'actualScoreG4': json['actual_score_g4'] == null ? undefined : json['actual_score_g4'],
        'percentG4': json['percent_g4'] == null ? undefined : json['percent_g4'],
        'percentWeightG4': json['percent_weight_g4'] == null ? undefined : json['percent_weight_g4'],
    };
}

export function LiquidityModelToJSON(json: any): LiquidityModel {
    return LiquidityModelToJSONTyped(json, false);
}

export function LiquidityModelToJSONTyped(value?: LiquidityModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_ratio': value['currentRatio'],
        'current_ratio_score': value['currentRatioScore'],
        'quick_ratio': value['quickRatio'],
        'quick_ratio_score': value['quickRatioScore'],
        'arturnover': value['arturnover'],
        'apturnover': value['apturnover'],
        'avgpaymentperiod': value['avgpaymentperiod'],
        'inventoryturnover': value['inventoryturnover'],
        'collectionperiod': value['collectionperiod'],
        'dayssalesinventory': value['dayssalesinventory'],
        'grossprofitmargin': value['grossprofitmargin'],
        'netprofitmargin': value['netprofitmargin'],
        'roa': value['roa'],
        'roe': value['roe'],
        'roe_score': value['roeScore'],
        'debt_ratio': value['debtRatio'],
        'debt_ratio_score': value['debtRatioScore'],
        'debttoequity': value['debttoequity'],
        'interestcoverage': value['interestcoverage'],
        'maxscore_g4': value['maxscoreG4'],
        'actual_score_g4': value['actualScoreG4'],
        'percent_g4': value['percentG4'],
        'percent_weight_g4': value['percentWeightG4'],
    };
}

