/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MasterCustomerModel } from './MasterCustomerModel';
import {
    MasterCustomerModelFromJSON,
    MasterCustomerModelFromJSONTyped,
    MasterCustomerModelToJSON,
    MasterCustomerModelToJSONTyped,
} from './MasterCustomerModel';

/**
 * 
 * @export
 * @interface MasterCustomerModelBaseResponseModel
 */
export interface MasterCustomerModelBaseResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof MasterCustomerModelBaseResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MasterCustomerModelBaseResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof MasterCustomerModelBaseResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {MasterCustomerModel}
     * @memberof MasterCustomerModelBaseResponseModel
     */
    data?: MasterCustomerModel;
}

/**
 * Check if a given object implements the MasterCustomerModelBaseResponseModel interface.
 */
export function instanceOfMasterCustomerModelBaseResponseModel(value: object): value is MasterCustomerModelBaseResponseModel {
    return true;
}

export function MasterCustomerModelBaseResponseModelFromJSON(json: any): MasterCustomerModelBaseResponseModel {
    return MasterCustomerModelBaseResponseModelFromJSONTyped(json, false);
}

export function MasterCustomerModelBaseResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MasterCustomerModelBaseResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'data': json['data'] == null ? undefined : MasterCustomerModelFromJSON(json['data']),
    };
}

export function MasterCustomerModelBaseResponseModelToJSON(json: any): MasterCustomerModelBaseResponseModel {
    return MasterCustomerModelBaseResponseModelToJSONTyped(json, false);
}

export function MasterCustomerModelBaseResponseModelToJSONTyped(value?: MasterCustomerModelBaseResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'data': MasterCustomerModelToJSON(value['data']),
    };
}

