/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MasterCustomerAttachModel
 */
export interface MasterCustomerAttachModel {
    /**
     * 
     * @type {number}
     * @memberof MasterCustomerAttachModel
     */
    companyId?: number;
    /**
     * 
     * @type {number}
     * @memberof MasterCustomerAttachModel
     */
    organizationId?: number;
    /**
     * 
     * @type {number}
     * @memberof MasterCustomerAttachModel
     */
    ownerUserId?: number;
    /**
     * 
     * @type {number}
     * @memberof MasterCustomerAttachModel
     */
    customerId?: number;
    /**
     * 
     * @type {number}
     * @memberof MasterCustomerAttachModel
     */
    fileNameId?: number;
    /**
     * 
     * @type {string}
     * @memberof MasterCustomerAttachModel
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof MasterCustomerAttachModel
     */
    filePath?: string;
    /**
     * 
     * @type {string}
     * @memberof MasterCustomerAttachModel
     */
    fileRemark?: string;
}

/**
 * Check if a given object implements the MasterCustomerAttachModel interface.
 */
export function instanceOfMasterCustomerAttachModel(value: object): value is MasterCustomerAttachModel {
    return true;
}

export function MasterCustomerAttachModelFromJSON(json: any): MasterCustomerAttachModel {
    return MasterCustomerAttachModelFromJSONTyped(json, false);
}

export function MasterCustomerAttachModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MasterCustomerAttachModel {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['company_id'] == null ? undefined : json['company_id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'ownerUserId': json['owner_user_id'] == null ? undefined : json['owner_user_id'],
        'customerId': json['customer_id'] == null ? undefined : json['customer_id'],
        'fileNameId': json['file_name_id'] == null ? undefined : json['file_name_id'],
        'fileName': json['file_name'] == null ? undefined : json['file_name'],
        'filePath': json['file_path'] == null ? undefined : json['file_path'],
        'fileRemark': json['file_remark'] == null ? undefined : json['file_remark'],
    };
}

export function MasterCustomerAttachModelToJSON(json: any): MasterCustomerAttachModel {
    return MasterCustomerAttachModelToJSONTyped(json, false);
}

export function MasterCustomerAttachModelToJSONTyped(value?: MasterCustomerAttachModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company_id': value['companyId'],
        'organization_id': value['organizationId'],
        'owner_user_id': value['ownerUserId'],
        'customer_id': value['customerId'],
        'file_name_id': value['fileNameId'],
        'file_name': value['fileName'],
        'file_path': value['filePath'],
        'file_remark': value['fileRemark'],
    };
}

