/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotiStepIdModel } from './NotiStepIdModel';
import {
    NotiStepIdModelFromJSON,
    NotiStepIdModelFromJSONTyped,
    NotiStepIdModelToJSON,
    NotiStepIdModelToJSONTyped,
} from './NotiStepIdModel';

/**
 * 
 * @export
 * @interface NotiStepIdModelBaseResponseModel
 */
export interface NotiStepIdModelBaseResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof NotiStepIdModelBaseResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotiStepIdModelBaseResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof NotiStepIdModelBaseResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {NotiStepIdModel}
     * @memberof NotiStepIdModelBaseResponseModel
     */
    data?: NotiStepIdModel;
}

/**
 * Check if a given object implements the NotiStepIdModelBaseResponseModel interface.
 */
export function instanceOfNotiStepIdModelBaseResponseModel(value: object): value is NotiStepIdModelBaseResponseModel {
    return true;
}

export function NotiStepIdModelBaseResponseModelFromJSON(json: any): NotiStepIdModelBaseResponseModel {
    return NotiStepIdModelBaseResponseModelFromJSONTyped(json, false);
}

export function NotiStepIdModelBaseResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotiStepIdModelBaseResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'data': json['data'] == null ? undefined : NotiStepIdModelFromJSON(json['data']),
    };
}

export function NotiStepIdModelBaseResponseModelToJSON(json: any): NotiStepIdModelBaseResponseModel {
    return NotiStepIdModelBaseResponseModelToJSONTyped(json, false);
}

export function NotiStepIdModelBaseResponseModelToJSONTyped(value?: NotiStepIdModelBaseResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'data': NotiStepIdModelToJSON(value['data']),
    };
}

