/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PaymentSOPStatus = {
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_11: 11,
    NUMBER_12: 12,
    NUMBER_13: 13,
    NUMBER_14: 14
} as const;
export type PaymentSOPStatus = typeof PaymentSOPStatus[keyof typeof PaymentSOPStatus];


export function instanceOfPaymentSOPStatus(value: any): boolean {
    for (const key in PaymentSOPStatus) {
        if (Object.prototype.hasOwnProperty.call(PaymentSOPStatus, key)) {
            if (PaymentSOPStatus[key as keyof typeof PaymentSOPStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PaymentSOPStatusFromJSON(json: any): PaymentSOPStatus {
    return PaymentSOPStatusFromJSONTyped(json, false);
}

export function PaymentSOPStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentSOPStatus {
    return json as PaymentSOPStatus;
}

export function PaymentSOPStatusToJSON(value?: PaymentSOPStatus | null): any {
    return value as any;
}

export function PaymentSOPStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): PaymentSOPStatus {
    return value as PaymentSOPStatus;
}

