/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProFileCreditModel
 */
export interface ProFileCreditModel {
    /**
     * 
     * @type {number}
     * @memberof ProFileCreditModel
     */
    totalScore?: number;
    /**
     * 
     * @type {string}
     * @memberof ProFileCreditModel
     */
    creditScore?: string;
    /**
     * 
     * @type {string}
     * @memberof ProFileCreditModel
     */
    grade?: string;
}

/**
 * Check if a given object implements the ProFileCreditModel interface.
 */
export function instanceOfProFileCreditModel(value: object): value is ProFileCreditModel {
    return true;
}

export function ProFileCreditModelFromJSON(json: any): ProFileCreditModel {
    return ProFileCreditModelFromJSONTyped(json, false);
}

export function ProFileCreditModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProFileCreditModel {
    if (json == null) {
        return json;
    }
    return {
        
        'totalScore': json['total_score'] == null ? undefined : json['total_score'],
        'creditScore': json['credit_score'] == null ? undefined : json['credit_score'],
        'grade': json['grade'] == null ? undefined : json['grade'],
    };
}

export function ProFileCreditModelToJSON(json: any): ProFileCreditModel {
    return ProFileCreditModelToJSONTyped(json, false);
}

export function ProFileCreditModelToJSONTyped(value?: ProFileCreditModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_score': value['totalScore'],
        'credit_score': value['creditScore'],
        'grade': value['grade'],
    };
}

