/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrnRbtCnarInhouseFileModel } from './TrnRbtCnarInhouseFileModel';
import {
    TrnRbtCnarInhouseFileModelFromJSON,
    TrnRbtCnarInhouseFileModelFromJSONTyped,
    TrnRbtCnarInhouseFileModelToJSON,
    TrnRbtCnarInhouseFileModelToJSONTyped,
} from './TrnRbtCnarInhouseFileModel';
import type { TrnRbtCnarInhouseModel } from './TrnRbtCnarInhouseModel';
import {
    TrnRbtCnarInhouseModelFromJSON,
    TrnRbtCnarInhouseModelFromJSONTyped,
    TrnRbtCnarInhouseModelToJSON,
    TrnRbtCnarInhouseModelToJSONTyped,
} from './TrnRbtCnarInhouseModel';

/**
 * 
 * @export
 * @interface RebateSendArcnInhFaModel
 */
export interface RebateSendArcnInhFaModel {
    /**
     * 
     * @type {Array<TrnRbtCnarInhouseModel>}
     * @memberof RebateSendArcnInhFaModel
     */
    trnRbtCnarInhouse?: Array<TrnRbtCnarInhouseModel>;
    /**
     * 
     * @type {Array<TrnRbtCnarInhouseFileModel>}
     * @memberof RebateSendArcnInhFaModel
     */
    trnRbtCnarInhouseFile?: Array<TrnRbtCnarInhouseFileModel>;
}

/**
 * Check if a given object implements the RebateSendArcnInhFaModel interface.
 */
export function instanceOfRebateSendArcnInhFaModel(value: object): value is RebateSendArcnInhFaModel {
    return true;
}

export function RebateSendArcnInhFaModelFromJSON(json: any): RebateSendArcnInhFaModel {
    return RebateSendArcnInhFaModelFromJSONTyped(json, false);
}

export function RebateSendArcnInhFaModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RebateSendArcnInhFaModel {
    if (json == null) {
        return json;
    }
    return {
        
        'trnRbtCnarInhouse': json['trn_rbt_cnar_inhouse'] == null ? undefined : ((json['trn_rbt_cnar_inhouse'] as Array<any>).map(TrnRbtCnarInhouseModelFromJSON)),
        'trnRbtCnarInhouseFile': json['trn_rbt_cnar_inhouse_file'] == null ? undefined : ((json['trn_rbt_cnar_inhouse_file'] as Array<any>).map(TrnRbtCnarInhouseFileModelFromJSON)),
    };
}

export function RebateSendArcnInhFaModelToJSON(json: any): RebateSendArcnInhFaModel {
    return RebateSendArcnInhFaModelToJSONTyped(json, false);
}

export function RebateSendArcnInhFaModelToJSONTyped(value?: RebateSendArcnInhFaModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trn_rbt_cnar_inhouse': value['trnRbtCnarInhouse'] == null ? undefined : ((value['trnRbtCnarInhouse'] as Array<any>).map(TrnRbtCnarInhouseModelToJSON)),
        'trn_rbt_cnar_inhouse_file': value['trnRbtCnarInhouseFile'] == null ? undefined : ((value['trnRbtCnarInhouseFile'] as Array<any>).map(TrnRbtCnarInhouseFileModelToJSON)),
    };
}

