/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RefType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type RefType = typeof RefType[keyof typeof RefType];


export function instanceOfRefType(value: any): boolean {
    for (const key in RefType) {
        if (Object.prototype.hasOwnProperty.call(RefType, key)) {
            if (RefType[key as keyof typeof RefType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RefTypeFromJSON(json: any): RefType {
    return RefTypeFromJSONTyped(json, false);
}

export function RefTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefType {
    return json as RefType;
}

export function RefTypeToJSON(value?: RefType | null): any {
    return value as any;
}

export function RefTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): RefType {
    return value as RefType;
}

