/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegisterCustomerUpdateModel } from './RegisterCustomerUpdateModel';
import {
    RegisterCustomerUpdateModelFromJSON,
    RegisterCustomerUpdateModelFromJSONTyped,
    RegisterCustomerUpdateModelToJSON,
    RegisterCustomerUpdateModelToJSONTyped,
} from './RegisterCustomerUpdateModel';

/**
 * 
 * @export
 * @interface RegisterCustomerUpdateModelBaseResponseModel
 */
export interface RegisterCustomerUpdateModelBaseResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof RegisterCustomerUpdateModelBaseResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegisterCustomerUpdateModelBaseResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof RegisterCustomerUpdateModelBaseResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {RegisterCustomerUpdateModel}
     * @memberof RegisterCustomerUpdateModelBaseResponseModel
     */
    data?: RegisterCustomerUpdateModel;
}

/**
 * Check if a given object implements the RegisterCustomerUpdateModelBaseResponseModel interface.
 */
export function instanceOfRegisterCustomerUpdateModelBaseResponseModel(value: object): value is RegisterCustomerUpdateModelBaseResponseModel {
    return true;
}

export function RegisterCustomerUpdateModelBaseResponseModelFromJSON(json: any): RegisterCustomerUpdateModelBaseResponseModel {
    return RegisterCustomerUpdateModelBaseResponseModelFromJSONTyped(json, false);
}

export function RegisterCustomerUpdateModelBaseResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterCustomerUpdateModelBaseResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'data': json['data'] == null ? undefined : RegisterCustomerUpdateModelFromJSON(json['data']),
    };
}

export function RegisterCustomerUpdateModelBaseResponseModelToJSON(json: any): RegisterCustomerUpdateModelBaseResponseModel {
    return RegisterCustomerUpdateModelBaseResponseModelToJSONTyped(json, false);
}

export function RegisterCustomerUpdateModelBaseResponseModelToJSONTyped(value?: RegisterCustomerUpdateModelBaseResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'data': RegisterCustomerUpdateModelToJSON(value['data']),
    };
}

