/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bankremain } from './Bankremain';
import {
    BankremainFromJSON,
    BankremainFromJSONTyped,
    BankremainToJSON,
    BankremainToJSONTyped,
} from './Bankremain';

/**
 * 
 * @export
 * @interface ReportBankReconcileModel
 */
export interface ReportBankReconcileModel {
    /**
     * 
     * @type {number}
     * @memberof ReportBankReconcileModel
     */
    bankAccountId?: number;
    /**
     * 
     * @type {string}
     * @memberof ReportBankReconcileModel
     */
    unit?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportBankReconcileModel
     */
    orgNameTh?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportBankReconcileModel
     */
    bankAccountName?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportBankReconcileModel
     */
    glAccountName?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportBankReconcileModel
     */
    endDate?: string;
    /**
     * 
     * @type {number}
     * @memberof ReportBankReconcileModel
     */
    accountRemain?: number;
    /**
     * 
     * @type {Array<Bankremain>}
     * @memberof ReportBankReconcileModel
     */
    bankRemainPlus?: Array<Bankremain>;
    /**
     * 
     * @type {number}
     * @memberof ReportBankReconcileModel
     */
    sumBankRemainPlus?: number;
    /**
     * 
     * @type {Array<Bankremain>}
     * @memberof ReportBankReconcileModel
     */
    bankRemainMinus?: Array<Bankremain>;
    /**
     * 
     * @type {number}
     * @memberof ReportBankReconcileModel
     */
    sumBankRemainMinus?: number;
    /**
     * 
     * @type {Array<Bankremain>}
     * @memberof ReportBankReconcileModel
     */
    accountRemainPlus?: Array<Bankremain>;
    /**
     * 
     * @type {number}
     * @memberof ReportBankReconcileModel
     */
    sumAccountRemainPlus?: number;
    /**
     * 
     * @type {Array<Bankremain>}
     * @memberof ReportBankReconcileModel
     */
    accountRemainMinus?: Array<Bankremain>;
    /**
     * 
     * @type {number}
     * @memberof ReportBankReconcileModel
     */
    sumAccountRemainMinus?: number;
    /**
     * 
     * @type {number}
     * @memberof ReportBankReconcileModel
     */
    bankRemain?: number;
    /**
     * 
     * @type {number}
     * @memberof ReportBankReconcileModel
     */
    otherRemainPlus?: number;
    /**
     * 
     * @type {number}
     * @memberof ReportBankReconcileModel
     */
    otherRemainMinus?: number;
}

/**
 * Check if a given object implements the ReportBankReconcileModel interface.
 */
export function instanceOfReportBankReconcileModel(value: object): value is ReportBankReconcileModel {
    return true;
}

export function ReportBankReconcileModelFromJSON(json: any): ReportBankReconcileModel {
    return ReportBankReconcileModelFromJSONTyped(json, false);
}

export function ReportBankReconcileModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportBankReconcileModel {
    if (json == null) {
        return json;
    }
    return {
        
        'bankAccountId': json['bank_account_id'] == null ? undefined : json['bank_account_id'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'orgNameTh': json['org_name_th'] == null ? undefined : json['org_name_th'],
        'bankAccountName': json['bank_account_name'] == null ? undefined : json['bank_account_name'],
        'glAccountName': json['gl_account_name'] == null ? undefined : json['gl_account_name'],
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'accountRemain': json['account_remain'] == null ? undefined : json['account_remain'],
        'bankRemainPlus': json['bank_remain_plus'] == null ? undefined : ((json['bank_remain_plus'] as Array<any>).map(BankremainFromJSON)),
        'sumBankRemainPlus': json['sum_bank_remain_plus'] == null ? undefined : json['sum_bank_remain_plus'],
        'bankRemainMinus': json['bank_remain_minus'] == null ? undefined : ((json['bank_remain_minus'] as Array<any>).map(BankremainFromJSON)),
        'sumBankRemainMinus': json['sum_bank_remain_minus'] == null ? undefined : json['sum_bank_remain_minus'],
        'accountRemainPlus': json['account_remain_plus'] == null ? undefined : ((json['account_remain_plus'] as Array<any>).map(BankremainFromJSON)),
        'sumAccountRemainPlus': json['sum_account_remain_plus'] == null ? undefined : json['sum_account_remain_plus'],
        'accountRemainMinus': json['account_remain_minus'] == null ? undefined : ((json['account_remain_minus'] as Array<any>).map(BankremainFromJSON)),
        'sumAccountRemainMinus': json['sum_account_remain_minus'] == null ? undefined : json['sum_account_remain_minus'],
        'bankRemain': json['bank_remain'] == null ? undefined : json['bank_remain'],
        'otherRemainPlus': json['other_remain_plus'] == null ? undefined : json['other_remain_plus'],
        'otherRemainMinus': json['other_remain_minus'] == null ? undefined : json['other_remain_minus'],
    };
}

export function ReportBankReconcileModelToJSON(json: any): ReportBankReconcileModel {
    return ReportBankReconcileModelToJSONTyped(json, false);
}

export function ReportBankReconcileModelToJSONTyped(value?: ReportBankReconcileModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bank_account_id': value['bankAccountId'],
        'unit': value['unit'],
        'org_name_th': value['orgNameTh'],
        'bank_account_name': value['bankAccountName'],
        'gl_account_name': value['glAccountName'],
        'end_date': value['endDate'],
        'account_remain': value['accountRemain'],
        'bank_remain_plus': value['bankRemainPlus'] == null ? undefined : ((value['bankRemainPlus'] as Array<any>).map(BankremainToJSON)),
        'sum_bank_remain_plus': value['sumBankRemainPlus'],
        'bank_remain_minus': value['bankRemainMinus'] == null ? undefined : ((value['bankRemainMinus'] as Array<any>).map(BankremainToJSON)),
        'sum_bank_remain_minus': value['sumBankRemainMinus'],
        'account_remain_plus': value['accountRemainPlus'] == null ? undefined : ((value['accountRemainPlus'] as Array<any>).map(BankremainToJSON)),
        'sum_account_remain_plus': value['sumAccountRemainPlus'],
        'account_remain_minus': value['accountRemainMinus'] == null ? undefined : ((value['accountRemainMinus'] as Array<any>).map(BankremainToJSON)),
        'sum_account_remain_minus': value['sumAccountRemainMinus'],
        'bank_remain': value['bankRemain'],
        'other_remain_plus': value['otherRemainPlus'],
        'other_remain_minus': value['otherRemainMinus'],
    };
}

