/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestUnholdSearchGetSOModel } from './RequestUnholdSearchGetSOModel';
import {
    RequestUnholdSearchGetSOModelFromJSON,
    RequestUnholdSearchGetSOModelFromJSONTyped,
    RequestUnholdSearchGetSOModelToJSON,
    RequestUnholdSearchGetSOModelToJSONTyped,
} from './RequestUnholdSearchGetSOModel';

/**
 * 
 * @export
 * @interface RequestUnholdSearchGetSOModelBaseResponsePagination
 */
export interface RequestUnholdSearchGetSOModelBaseResponsePagination {
    /**
     * 
     * @type {boolean}
     * @memberof RequestUnholdSearchGetSOModelBaseResponsePagination
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RequestUnholdSearchGetSOModelBaseResponsePagination
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof RequestUnholdSearchGetSOModelBaseResponsePagination
     */
    statusCode?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestUnholdSearchGetSOModelBaseResponsePagination
     */
    pageIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestUnholdSearchGetSOModelBaseResponsePagination
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestUnholdSearchGetSOModelBaseResponsePagination
     */
    pageAll?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestUnholdSearchGetSOModelBaseResponsePagination
     */
    totalRecord?: number;
    /**
     * 
     * @type {Array<RequestUnholdSearchGetSOModel>}
     * @memberof RequestUnholdSearchGetSOModelBaseResponsePagination
     */
    data?: Array<RequestUnholdSearchGetSOModel>;
}

/**
 * Check if a given object implements the RequestUnholdSearchGetSOModelBaseResponsePagination interface.
 */
export function instanceOfRequestUnholdSearchGetSOModelBaseResponsePagination(value: object): value is RequestUnholdSearchGetSOModelBaseResponsePagination {
    return true;
}

export function RequestUnholdSearchGetSOModelBaseResponsePaginationFromJSON(json: any): RequestUnholdSearchGetSOModelBaseResponsePagination {
    return RequestUnholdSearchGetSOModelBaseResponsePaginationFromJSONTyped(json, false);
}

export function RequestUnholdSearchGetSOModelBaseResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestUnholdSearchGetSOModelBaseResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'pageIndex': json['pageIndex'] == null ? undefined : json['pageIndex'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageAll': json['pageAll'] == null ? undefined : json['pageAll'],
        'totalRecord': json['totalRecord'] == null ? undefined : json['totalRecord'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(RequestUnholdSearchGetSOModelFromJSON)),
    };
}

export function RequestUnholdSearchGetSOModelBaseResponsePaginationToJSON(json: any): RequestUnholdSearchGetSOModelBaseResponsePagination {
    return RequestUnholdSearchGetSOModelBaseResponsePaginationToJSONTyped(json, false);
}

export function RequestUnholdSearchGetSOModelBaseResponsePaginationToJSONTyped(value?: RequestUnholdSearchGetSOModelBaseResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'pageIndex': value['pageIndex'],
        'pageSize': value['pageSize'],
        'pageAll': value['pageAll'],
        'totalRecord': value['totalRecord'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(RequestUnholdSearchGetSOModelToJSON)),
    };
}

