/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestUpdateCustomerModel } from './RequestUpdateCustomerModel';
import {
    RequestUpdateCustomerModelFromJSON,
    RequestUpdateCustomerModelFromJSONTyped,
    RequestUpdateCustomerModelToJSON,
    RequestUpdateCustomerModelToJSONTyped,
} from './RequestUpdateCustomerModel';

/**
 * 
 * @export
 * @interface RequestUpdateCustomerModelBaseResponseModel
 */
export interface RequestUpdateCustomerModelBaseResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof RequestUpdateCustomerModelBaseResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RequestUpdateCustomerModelBaseResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof RequestUpdateCustomerModelBaseResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {RequestUpdateCustomerModel}
     * @memberof RequestUpdateCustomerModelBaseResponseModel
     */
    data?: RequestUpdateCustomerModel;
}

/**
 * Check if a given object implements the RequestUpdateCustomerModelBaseResponseModel interface.
 */
export function instanceOfRequestUpdateCustomerModelBaseResponseModel(value: object): value is RequestUpdateCustomerModelBaseResponseModel {
    return true;
}

export function RequestUpdateCustomerModelBaseResponseModelFromJSON(json: any): RequestUpdateCustomerModelBaseResponseModel {
    return RequestUpdateCustomerModelBaseResponseModelFromJSONTyped(json, false);
}

export function RequestUpdateCustomerModelBaseResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestUpdateCustomerModelBaseResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'data': json['data'] == null ? undefined : RequestUpdateCustomerModelFromJSON(json['data']),
    };
}

export function RequestUpdateCustomerModelBaseResponseModelToJSON(json: any): RequestUpdateCustomerModelBaseResponseModel {
    return RequestUpdateCustomerModelBaseResponseModelToJSONTyped(json, false);
}

export function RequestUpdateCustomerModelBaseResponseModelToJSONTyped(value?: RequestUpdateCustomerModelBaseResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'data': RequestUpdateCustomerModelToJSON(value['data']),
    };
}

