/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RequestUpdateCustomerStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type RequestUpdateCustomerStatus = typeof RequestUpdateCustomerStatus[keyof typeof RequestUpdateCustomerStatus];


export function instanceOfRequestUpdateCustomerStatus(value: any): boolean {
    for (const key in RequestUpdateCustomerStatus) {
        if (Object.prototype.hasOwnProperty.call(RequestUpdateCustomerStatus, key)) {
            if (RequestUpdateCustomerStatus[key as keyof typeof RequestUpdateCustomerStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RequestUpdateCustomerStatusFromJSON(json: any): RequestUpdateCustomerStatus {
    return RequestUpdateCustomerStatusFromJSONTyped(json, false);
}

export function RequestUpdateCustomerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestUpdateCustomerStatus {
    return json as RequestUpdateCustomerStatus;
}

export function RequestUpdateCustomerStatusToJSON(value?: RequestUpdateCustomerStatus | null): any {
    return value as any;
}

export function RequestUpdateCustomerStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): RequestUpdateCustomerStatus {
    return value as RequestUpdateCustomerStatus;
}

