/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MenuResponseModel } from './MenuResponseModel';
import {
    MenuResponseModelFromJSON,
    MenuResponseModelFromJSONTyped,
    MenuResponseModelToJSON,
    MenuResponseModelToJSONTyped,
} from './MenuResponseModel';
import type { PermissionResponseModel } from './PermissionResponseModel';
import {
    PermissionResponseModelFromJSON,
    PermissionResponseModelFromJSONTyped,
    PermissionResponseModelToJSON,
    PermissionResponseModelToJSONTyped,
} from './PermissionResponseModel';

/**
 * 
 * @export
 * @interface RolePermissionRequestModel
 */
export interface RolePermissionRequestModel {
    /**
     * 
     * @type {number}
     * @memberof RolePermissionRequestModel
     */
    roleId?: number;
    /**
     * 
     * @type {Array<MenuResponseModel>}
     * @memberof RolePermissionRequestModel
     */
    menus?: Array<MenuResponseModel>;
    /**
     * 
     * @type {Array<PermissionResponseModel>}
     * @memberof RolePermissionRequestModel
     */
    permissions?: Array<PermissionResponseModel>;
}

/**
 * Check if a given object implements the RolePermissionRequestModel interface.
 */
export function instanceOfRolePermissionRequestModel(value: object): value is RolePermissionRequestModel {
    return true;
}

export function RolePermissionRequestModelFromJSON(json: any): RolePermissionRequestModel {
    return RolePermissionRequestModelFromJSONTyped(json, false);
}

export function RolePermissionRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RolePermissionRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'roleId': json['role_id'] == null ? undefined : json['role_id'],
        'menus': json['menus'] == null ? undefined : ((json['menus'] as Array<any>).map(MenuResponseModelFromJSON)),
        'permissions': json['permissions'] == null ? undefined : ((json['permissions'] as Array<any>).map(PermissionResponseModelFromJSON)),
    };
}

export function RolePermissionRequestModelToJSON(json: any): RolePermissionRequestModel {
    return RolePermissionRequestModelToJSONTyped(json, false);
}

export function RolePermissionRequestModelToJSONTyped(value?: RolePermissionRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role_id': value['roleId'],
        'menus': value['menus'] == null ? undefined : ((value['menus'] as Array<any>).map(MenuResponseModelToJSON)),
        'permissions': value['permissions'] == null ? undefined : ((value['permissions'] as Array<any>).map(PermissionResponseModelToJSON)),
    };
}

