/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EvaluationConfigType } from './EvaluationConfigType';
import {
    EvaluationConfigTypeFromJSON,
    EvaluationConfigTypeFromJSONTyped,
    EvaluationConfigTypeToJSON,
    EvaluationConfigTypeToJSONTyped,
} from './EvaluationConfigType';

/**
 * 
 * @export
 * @interface SysCustomerEvaluationConfigGetSearchModel
 */
export interface SysCustomerEvaluationConfigGetSearchModel {
    /**
     * 
     * @type {number}
     * @memberof SysCustomerEvaluationConfigGetSearchModel
     */
    rowNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof SysCustomerEvaluationConfigGetSearchModel
     */
    customerEvaluationConfigId?: number;
    /**
     * 
     * @type {string}
     * @memberof SysCustomerEvaluationConfigGetSearchModel
     */
    evaluationName?: string;
    /**
     * 
     * @type {EvaluationConfigType}
     * @memberof SysCustomerEvaluationConfigGetSearchModel
     */
    evaluationConfigType?: EvaluationConfigType;
    /**
     * 
     * @type {string}
     * @memberof SysCustomerEvaluationConfigGetSearchModel
     */
    readonly evaluationConfigTypeName?: string;
}



/**
 * Check if a given object implements the SysCustomerEvaluationConfigGetSearchModel interface.
 */
export function instanceOfSysCustomerEvaluationConfigGetSearchModel(value: object): value is SysCustomerEvaluationConfigGetSearchModel {
    return true;
}

export function SysCustomerEvaluationConfigGetSearchModelFromJSON(json: any): SysCustomerEvaluationConfigGetSearchModel {
    return SysCustomerEvaluationConfigGetSearchModelFromJSONTyped(json, false);
}

export function SysCustomerEvaluationConfigGetSearchModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SysCustomerEvaluationConfigGetSearchModel {
    if (json == null) {
        return json;
    }
    return {
        
        'rowNumber': json['row_number'] == null ? undefined : json['row_number'],
        'customerEvaluationConfigId': json['customer_evaluation_config_id'] == null ? undefined : json['customer_evaluation_config_id'],
        'evaluationName': json['evaluation_name'] == null ? undefined : json['evaluation_name'],
        'evaluationConfigType': json['evaluation_config_type'] == null ? undefined : EvaluationConfigTypeFromJSON(json['evaluation_config_type']),
        'evaluationConfigTypeName': json['evaluation_config_type_name'] == null ? undefined : json['evaluation_config_type_name'],
    };
}

export function SysCustomerEvaluationConfigGetSearchModelToJSON(json: any): SysCustomerEvaluationConfigGetSearchModel {
    return SysCustomerEvaluationConfigGetSearchModelToJSONTyped(json, false);
}

export function SysCustomerEvaluationConfigGetSearchModelToJSONTyped(value?: Omit<SysCustomerEvaluationConfigGetSearchModel, 'evaluation_config_type_name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row_number': value['rowNumber'],
        'customer_evaluation_config_id': value['customerEvaluationConfigId'],
        'evaluation_name': value['evaluationName'],
        'evaluation_config_type': EvaluationConfigTypeToJSON(value['evaluationConfigType']),
    };
}

