/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TotalSummaryDetail
 */
export interface TotalSummaryDetail {
    /**
     * 
     * @type {number}
     * @memberof TotalSummaryDetail
     */
    totalSummary?: number;
}

/**
 * Check if a given object implements the TotalSummaryDetail interface.
 */
export function instanceOfTotalSummaryDetail(value: object): value is TotalSummaryDetail {
    return true;
}

export function TotalSummaryDetailFromJSON(json: any): TotalSummaryDetail {
    return TotalSummaryDetailFromJSONTyped(json, false);
}

export function TotalSummaryDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): TotalSummaryDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'totalSummary': json['total_summary'] == null ? undefined : json['total_summary'],
    };
}

export function TotalSummaryDetailToJSON(json: any): TotalSummaryDetail {
    return TotalSummaryDetailToJSONTyped(json, false);
}

export function TotalSummaryDetailToJSONTyped(value?: TotalSummaryDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_summary': value['totalSummary'],
    };
}

