/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentTravelStatus } from './PaymentTravelStatus';
import {
    PaymentTravelStatusFromJSON,
    PaymentTravelStatusFromJSONTyped,
    PaymentTravelStatusToJSON,
    PaymentTravelStatusToJSONTyped,
} from './PaymentTravelStatus';
import type { TravelEngineerDetailListModel } from './TravelEngineerDetailListModel';
import {
    TravelEngineerDetailListModelFromJSON,
    TravelEngineerDetailListModelFromJSONTyped,
    TravelEngineerDetailListModelToJSON,
    TravelEngineerDetailListModelToJSONTyped,
} from './TravelEngineerDetailListModel';
import type { TotalSummaryDetail } from './TotalSummaryDetail';
import {
    TotalSummaryDetailFromJSON,
    TotalSummaryDetailFromJSONTyped,
    TotalSummaryDetailToJSON,
    TotalSummaryDetailToJSONTyped,
} from './TotalSummaryDetail';
import type { TravelSummaryHistoryModel } from './TravelSummaryHistoryModel';
import {
    TravelSummaryHistoryModelFromJSON,
    TravelSummaryHistoryModelFromJSONTyped,
    TravelSummaryHistoryModelToJSON,
    TravelSummaryHistoryModelToJSONTyped,
} from './TravelSummaryHistoryModel';
import type { TravelSummaryTotalDetail } from './TravelSummaryTotalDetail';
import {
    TravelSummaryTotalDetailFromJSON,
    TravelSummaryTotalDetailFromJSONTyped,
    TravelSummaryTotalDetailToJSON,
    TravelSummaryTotalDetailToJSONTyped,
} from './TravelSummaryTotalDetail';

/**
 * 
 * @export
 * @interface TravelSummaryDataModel
 */
export interface TravelSummaryDataModel {
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    rowNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    reqTravelId?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    companyId?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    paymentCompanyId?: number;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    paymentCompany?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    paymentCompanyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    paymentCompanyName?: string;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    paymentTravelMonth?: number;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    paymentTravelMonthName?: string;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    paymentTravelYear?: number;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    readonly paymentTravelYearStr?: string;
    /**
     * 
     * @type {Date}
     * @memberof TravelSummaryDataModel
     */
    createDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    paymentGasPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    numberOfEngineer?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    numberOfInvoice?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    numberOfJob?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    amountOfMoney?: number;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    paymentTravelRemark?: string;
    /**
     * 
     * @type {PaymentTravelStatus}
     * @memberof TravelSummaryDataModel
     */
    paymentTravelStatus?: PaymentTravelStatus;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    paymentTravelStatusName?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    fileAttachment1?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    fileAttachment2?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    fileAttachment3?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    companyPayroll?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    consumtionRateUnit?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    oilCostPriceUnit?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    oilCostSummaryUnit?: string;
    /**
     * 
     * @type {Date}
     * @memberof TravelSummaryDataModel
     */
    paymentSendDate?: Date;
    /**
     * 
     * @type {Array<TotalSummaryDetail>}
     * @memberof TravelSummaryDataModel
     */
    totalSummaryDetail?: Array<TotalSummaryDetail>;
    /**
     * 
     * @type {TravelSummaryTotalDetail}
     * @memberof TravelSummaryDataModel
     */
    summarySubDetail?: TravelSummaryTotalDetail;
    /**
     * 
     * @type {Array<TravelEngineerDetailListModel>}
     * @memberof TravelSummaryDataModel
     */
    summarySubDetailList?: Array<TravelEngineerDetailListModel>;
    /**
     * 
     * @type {Array<TravelSummaryHistoryModel>}
     * @memberof TravelSummaryDataModel
     */
    travelSummaryHistory?: Array<TravelSummaryHistoryModel>;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    workflowId?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    currentStepId?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    reqOilRoundId?: number;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryDataModel
     */
    rejectReason?: string;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    breakageRate?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelSummaryDataModel
     */
    oilCostRate?: number;
}



/**
 * Check if a given object implements the TravelSummaryDataModel interface.
 */
export function instanceOfTravelSummaryDataModel(value: object): value is TravelSummaryDataModel {
    return true;
}

export function TravelSummaryDataModelFromJSON(json: any): TravelSummaryDataModel {
    return TravelSummaryDataModelFromJSONTyped(json, false);
}

export function TravelSummaryDataModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelSummaryDataModel {
    if (json == null) {
        return json;
    }
    return {
        
        'rowNumber': json['row_number'] == null ? undefined : json['row_number'],
        'reqTravelId': json['req_travel_id'] == null ? undefined : json['req_travel_id'],
        'companyId': json['company_id'] == null ? undefined : json['company_id'],
        'paymentCompanyId': json['payment_company_id'] == null ? undefined : json['payment_company_id'],
        'paymentCompany': json['payment_company'] == null ? undefined : json['payment_company'],
        'paymentCompanyCode': json['payment_company_code'] == null ? undefined : json['payment_company_code'],
        'paymentCompanyName': json['payment_company_name'] == null ? undefined : json['payment_company_name'],
        'paymentTravelMonth': json['payment_travel_month'] == null ? undefined : json['payment_travel_month'],
        'paymentTravelMonthName': json['payment_travel_month_name'] == null ? undefined : json['payment_travel_month_name'],
        'paymentTravelYear': json['payment_travel_year'] == null ? undefined : json['payment_travel_year'],
        'paymentTravelYearStr': json['payment_travel_year_str'] == null ? undefined : json['payment_travel_year_str'],
        'createDate': json['create_date'] == null ? undefined : (new Date(json['create_date'])),
        'paymentGasPrice': json['payment_gas_price'] == null ? undefined : json['payment_gas_price'],
        'numberOfEngineer': json['number_of_engineer'] == null ? undefined : json['number_of_engineer'],
        'numberOfInvoice': json['number_of_invoice'] == null ? undefined : json['number_of_invoice'],
        'numberOfJob': json['number_of_job'] == null ? undefined : json['number_of_job'],
        'amountOfMoney': json['amount_of_money'] == null ? undefined : json['amount_of_money'],
        'paymentTravelRemark': json['payment_travel_remark'] == null ? undefined : json['payment_travel_remark'],
        'paymentTravelStatus': json['payment_travel_status'] == null ? undefined : PaymentTravelStatusFromJSON(json['payment_travel_status']),
        'paymentTravelStatusName': json['payment_travel_status_name'] == null ? undefined : json['payment_travel_status_name'],
        'fileAttachment1': json['file_attachment_1'] == null ? undefined : json['file_attachment_1'],
        'fileAttachment2': json['file_attachment_2'] == null ? undefined : json['file_attachment_2'],
        'fileAttachment3': json['file_attachment_3'] == null ? undefined : json['file_attachment_3'],
        'companyPayroll': json['company_payroll'] == null ? undefined : json['company_payroll'],
        'consumtionRateUnit': json['consumtion_rate_unit'] == null ? undefined : json['consumtion_rate_unit'],
        'oilCostPriceUnit': json['oil_cost_price_unit'] == null ? undefined : json['oil_cost_price_unit'],
        'oilCostSummaryUnit': json['oil_cost_summary_unit'] == null ? undefined : json['oil_cost_summary_unit'],
        'paymentSendDate': json['payment_send_date'] == null ? undefined : (new Date(json['payment_send_date'])),
        'totalSummaryDetail': json['total_summary_detail'] == null ? undefined : ((json['total_summary_detail'] as Array<any>).map(TotalSummaryDetailFromJSON)),
        'summarySubDetail': json['summary_sub_detail'] == null ? undefined : TravelSummaryTotalDetailFromJSON(json['summary_sub_detail']),
        'summarySubDetailList': json['summary_sub_detail_list'] == null ? undefined : ((json['summary_sub_detail_list'] as Array<any>).map(TravelEngineerDetailListModelFromJSON)),
        'travelSummaryHistory': json['travel_summary_history'] == null ? undefined : ((json['travel_summary_history'] as Array<any>).map(TravelSummaryHistoryModelFromJSON)),
        'workflowId': json['workflow_id'] == null ? undefined : json['workflow_id'],
        'currentStepId': json['current_step_id'] == null ? undefined : json['current_step_id'],
        'reqOilRoundId': json['req_oil_round_id'] == null ? undefined : json['req_oil_round_id'],
        'rejectReason': json['reject_reason'] == null ? undefined : json['reject_reason'],
        'breakageRate': json['breakage_rate'] == null ? undefined : json['breakage_rate'],
        'oilCostRate': json['oil_cost_rate'] == null ? undefined : json['oil_cost_rate'],
    };
}

export function TravelSummaryDataModelToJSON(json: any): TravelSummaryDataModel {
    return TravelSummaryDataModelToJSONTyped(json, false);
}

export function TravelSummaryDataModelToJSONTyped(value?: Omit<TravelSummaryDataModel, 'payment_travel_year_str'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row_number': value['rowNumber'],
        'req_travel_id': value['reqTravelId'],
        'company_id': value['companyId'],
        'payment_company_id': value['paymentCompanyId'],
        'payment_company': value['paymentCompany'],
        'payment_company_code': value['paymentCompanyCode'],
        'payment_company_name': value['paymentCompanyName'],
        'payment_travel_month': value['paymentTravelMonth'],
        'payment_travel_month_name': value['paymentTravelMonthName'],
        'payment_travel_year': value['paymentTravelYear'],
        'create_date': value['createDate'] == null ? undefined : ((value['createDate']).toISOString()),
        'payment_gas_price': value['paymentGasPrice'],
        'number_of_engineer': value['numberOfEngineer'],
        'number_of_invoice': value['numberOfInvoice'],
        'number_of_job': value['numberOfJob'],
        'amount_of_money': value['amountOfMoney'],
        'payment_travel_remark': value['paymentTravelRemark'],
        'payment_travel_status': PaymentTravelStatusToJSON(value['paymentTravelStatus']),
        'payment_travel_status_name': value['paymentTravelStatusName'],
        'file_attachment_1': value['fileAttachment1'],
        'file_attachment_2': value['fileAttachment2'],
        'file_attachment_3': value['fileAttachment3'],
        'company_payroll': value['companyPayroll'],
        'consumtion_rate_unit': value['consumtionRateUnit'],
        'oil_cost_price_unit': value['oilCostPriceUnit'],
        'oil_cost_summary_unit': value['oilCostSummaryUnit'],
        'payment_send_date': value['paymentSendDate'] == null ? undefined : ((value['paymentSendDate']).toISOString()),
        'total_summary_detail': value['totalSummaryDetail'] == null ? undefined : ((value['totalSummaryDetail'] as Array<any>).map(TotalSummaryDetailToJSON)),
        'summary_sub_detail': TravelSummaryTotalDetailToJSON(value['summarySubDetail']),
        'summary_sub_detail_list': value['summarySubDetailList'] == null ? undefined : ((value['summarySubDetailList'] as Array<any>).map(TravelEngineerDetailListModelToJSON)),
        'travel_summary_history': value['travelSummaryHistory'] == null ? undefined : ((value['travelSummaryHistory'] as Array<any>).map(TravelSummaryHistoryModelToJSON)),
        'workflow_id': value['workflowId'],
        'current_step_id': value['currentStepId'],
        'req_oil_round_id': value['reqOilRoundId'],
        'reject_reason': value['rejectReason'],
        'breakage_rate': value['breakageRate'],
        'oil_cost_rate': value['oilCostRate'],
    };
}

