/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TravelEngineerDetailListModel
 */
export interface TravelEngineerDetailListModel {
    /**
     * 
     * @type {number}
     * @memberof TravelEngineerDetailListModel
     */
    reqTravelEngineerId?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelEngineerDetailListModel
     */
    rowNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelEngineerDetailListModel
     */
    reqTravelId?: number;
    /**
     * 
     * @type {string}
     * @memberof TravelEngineerDetailListModel
     */
    engineerCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelEngineerDetailListModel
     */
    engineerName?: string;
    /**
     * 
     * @type {number}
     * @memberof TravelEngineerDetailListModel
     */
    numberOfInvoice?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelEngineerDetailListModel
     */
    numberOfJob?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelEngineerDetailListModel
     */
    amountOfMoney?: number;
    /**
     * 
     * @type {number}
     * @memberof TravelEngineerDetailListModel
     */
    lastAmountOfMoney?: number;
    /**
     * 
     * @type {string}
     * @memberof TravelEngineerDetailListModel
     */
    costDistanct?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelEngineerDetailListModel
     */
    costDistanctSign?: string;
}

/**
 * Check if a given object implements the TravelEngineerDetailListModel interface.
 */
export function instanceOfTravelEngineerDetailListModel(value: object): value is TravelEngineerDetailListModel {
    return true;
}

export function TravelEngineerDetailListModelFromJSON(json: any): TravelEngineerDetailListModel {
    return TravelEngineerDetailListModelFromJSONTyped(json, false);
}

export function TravelEngineerDetailListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelEngineerDetailListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'reqTravelEngineerId': json['req_travel_engineer_id'] == null ? undefined : json['req_travel_engineer_id'],
        'rowNumber': json['row_number'] == null ? undefined : json['row_number'],
        'reqTravelId': json['req_travel_id'] == null ? undefined : json['req_travel_id'],
        'engineerCode': json['engineer_code'] == null ? undefined : json['engineer_code'],
        'engineerName': json['engineer_name'] == null ? undefined : json['engineer_name'],
        'numberOfInvoice': json['number_of_invoice'] == null ? undefined : json['number_of_invoice'],
        'numberOfJob': json['number_of_job'] == null ? undefined : json['number_of_job'],
        'amountOfMoney': json['amount_of_money'] == null ? undefined : json['amount_of_money'],
        'lastAmountOfMoney': json['last_amount_of_money'] == null ? undefined : json['last_amount_of_money'],
        'costDistanct': json['cost_distanct'] == null ? undefined : json['cost_distanct'],
        'costDistanctSign': json['cost_distanct_sign'] == null ? undefined : json['cost_distanct_sign'],
    };
}

export function TravelEngineerDetailListModelToJSON(json: any): TravelEngineerDetailListModel {
    return TravelEngineerDetailListModelToJSONTyped(json, false);
}

export function TravelEngineerDetailListModelToJSONTyped(value?: TravelEngineerDetailListModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'req_travel_engineer_id': value['reqTravelEngineerId'],
        'row_number': value['rowNumber'],
        'req_travel_id': value['reqTravelId'],
        'engineer_code': value['engineerCode'],
        'engineer_name': value['engineerName'],
        'number_of_invoice': value['numberOfInvoice'],
        'number_of_job': value['numberOfJob'],
        'amount_of_money': value['amountOfMoney'],
        'last_amount_of_money': value['lastAmountOfMoney'],
        'cost_distanct': value['costDistanct'],
        'cost_distanct_sign': value['costDistanctSign'],
    };
}

