/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TravelSummaryHistoryModel
 */
export interface TravelSummaryHistoryModel {
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryHistoryModel
     */
    logStatusName?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryHistoryModel
     */
    updatedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryHistoryModel
     */
    updatedDate?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryHistoryModel
     */
    transitionLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof TravelSummaryHistoryModel
     */
    transitionType?: string;
}

/**
 * Check if a given object implements the TravelSummaryHistoryModel interface.
 */
export function instanceOfTravelSummaryHistoryModel(value: object): value is TravelSummaryHistoryModel {
    return true;
}

export function TravelSummaryHistoryModelFromJSON(json: any): TravelSummaryHistoryModel {
    return TravelSummaryHistoryModelFromJSONTyped(json, false);
}

export function TravelSummaryHistoryModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelSummaryHistoryModel {
    if (json == null) {
        return json;
    }
    return {
        
        'logStatusName': json['log_status_name'] == null ? undefined : json['log_status_name'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'updatedDate': json['updated_date'] == null ? undefined : json['updated_date'],
        'transitionLabel': json['transition_label'] == null ? undefined : json['transition_label'],
        'transitionType': json['transition_type'] == null ? undefined : json['transition_type'],
    };
}

export function TravelSummaryHistoryModelToJSON(json: any): TravelSummaryHistoryModel {
    return TravelSummaryHistoryModelToJSONTyped(json, false);
}

export function TravelSummaryHistoryModelToJSONTyped(value?: TravelSummaryHistoryModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'log_status_name': value['logStatusName'],
        'updated_by': value['updatedBy'],
        'updated_date': value['updatedDate'],
        'transition_label': value['transitionLabel'],
        'transition_type': value['transitionType'],
    };
}

