/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrnRbtCnarInhouseModel
 */
export interface TrnRbtCnarInhouseModel {
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    companyId?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    organizationId?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    ownerUserId?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    cnDealerCreateId?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    rebateCampaignId?: number;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    campaignName?: string;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    campaignTypeName?: string;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    supConSale?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    supConQty?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    rebateCalculateType?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    actualSale?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    actualQty?: number;
    /**
     * 
     * @type {Date}
     * @memberof TrnRbtCnarInhouseModel
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TrnRbtCnarInhouseModel
     */
    endDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TrnRbtCnarInhouseModel
     */
    conPeriodStart?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TrnRbtCnarInhouseModel
     */
    conPeriodEnd?: Date;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    estRebateAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    cnDealerCreateListId?: number;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    cnNo?: string;
    /**
     * 
     * @type {Date}
     * @memberof TrnRbtCnarInhouseModel
     */
    cnDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    cnAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    vat?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    cnAmountCur?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    vatCur?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    currencyId?: number;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    currencyAbbr?: string;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    exchangeRate?: number;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    customerCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    customerName?: string;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    taxPayerId?: string;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    revenueBranchCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    fullAddress?: string;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    provinceId?: number;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    provinceName?: string;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    districtId?: number;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    districtName?: string;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    subDistrictId?: number;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    subDistrictName?: string;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    zipCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    telephone?: string;
    /**
     * 
     * @type {string}
     * @memberof TrnRbtCnarInhouseModel
     */
    email?: string;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    workflowId?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    currentStepId?: number;
    /**
     * 
     * @type {number}
     * @memberof TrnRbtCnarInhouseModel
     */
    trnStatus?: number;
}

/**
 * Check if a given object implements the TrnRbtCnarInhouseModel interface.
 */
export function instanceOfTrnRbtCnarInhouseModel(value: object): value is TrnRbtCnarInhouseModel {
    return true;
}

export function TrnRbtCnarInhouseModelFromJSON(json: any): TrnRbtCnarInhouseModel {
    return TrnRbtCnarInhouseModelFromJSONTyped(json, false);
}

export function TrnRbtCnarInhouseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrnRbtCnarInhouseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['company_id'] == null ? undefined : json['company_id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'ownerUserId': json['owner_user_id'] == null ? undefined : json['owner_user_id'],
        'cnDealerCreateId': json['cn_dealer_create_id'] == null ? undefined : json['cn_dealer_create_id'],
        'rebateCampaignId': json['rebate_campaign_id'] == null ? undefined : json['rebate_campaign_id'],
        'campaignName': json['campaign_name'] == null ? undefined : json['campaign_name'],
        'campaignTypeName': json['campaign_type_name'] == null ? undefined : json['campaign_type_name'],
        'supConSale': json['sup_con_sale'] == null ? undefined : json['sup_con_sale'],
        'supConQty': json['sup_con_qty'] == null ? undefined : json['sup_con_qty'],
        'rebateCalculateType': json['rebate_calculate_type'] == null ? undefined : json['rebate_calculate_type'],
        'actualSale': json['actual_sale'] == null ? undefined : json['actual_sale'],
        'actualQty': json['actual_qty'] == null ? undefined : json['actual_qty'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'conPeriodStart': json['con_period_start'] == null ? undefined : (new Date(json['con_period_start'])),
        'conPeriodEnd': json['con_period_end'] == null ? undefined : (new Date(json['con_period_end'])),
        'estRebateAmount': json['est_rebate_amount'] == null ? undefined : json['est_rebate_amount'],
        'cnDealerCreateListId': json['cn_dealer_create_list_id'] == null ? undefined : json['cn_dealer_create_list_id'],
        'cnNo': json['cn_no'] == null ? undefined : json['cn_no'],
        'cnDate': json['cn_date'] == null ? undefined : (new Date(json['cn_date'])),
        'cnAmount': json['cn_amount'] == null ? undefined : json['cn_amount'],
        'vat': json['vat'] == null ? undefined : json['vat'],
        'cnAmountCur': json['cn_amount_cur'] == null ? undefined : json['cn_amount_cur'],
        'vatCur': json['vat_cur'] == null ? undefined : json['vat_cur'],
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'currencyAbbr': json['currency_abbr'] == null ? undefined : json['currency_abbr'],
        'exchangeRate': json['exchange_rate'] == null ? undefined : json['exchange_rate'],
        'customerId': json['customer_id'] == null ? undefined : json['customer_id'],
        'customerCode': json['customer_code'] == null ? undefined : json['customer_code'],
        'customerName': json['customer_name'] == null ? undefined : json['customer_name'],
        'taxPayerId': json['tax_payer_id'] == null ? undefined : json['tax_payer_id'],
        'revenueBranchCode': json['revenue_branch_code'] == null ? undefined : json['revenue_branch_code'],
        'fullAddress': json['full_address'] == null ? undefined : json['full_address'],
        'provinceId': json['province_id'] == null ? undefined : json['province_id'],
        'provinceName': json['province_name'] == null ? undefined : json['province_name'],
        'districtId': json['district_id'] == null ? undefined : json['district_id'],
        'districtName': json['district_name'] == null ? undefined : json['district_name'],
        'subDistrictId': json['sub_district_id'] == null ? undefined : json['sub_district_id'],
        'subDistrictName': json['sub_district_name'] == null ? undefined : json['sub_district_name'],
        'zipCode': json['zip_code'] == null ? undefined : json['zip_code'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
        'email': json['email'] == null ? undefined : json['email'],
        'workflowId': json['workflow_id'] == null ? undefined : json['workflow_id'],
        'currentStepId': json['current_step_id'] == null ? undefined : json['current_step_id'],
        'trnStatus': json['trn_status'] == null ? undefined : json['trn_status'],
    };
}

export function TrnRbtCnarInhouseModelToJSON(json: any): TrnRbtCnarInhouseModel {
    return TrnRbtCnarInhouseModelToJSONTyped(json, false);
}

export function TrnRbtCnarInhouseModelToJSONTyped(value?: TrnRbtCnarInhouseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company_id': value['companyId'],
        'organization_id': value['organizationId'],
        'owner_user_id': value['ownerUserId'],
        'cn_dealer_create_id': value['cnDealerCreateId'],
        'rebate_campaign_id': value['rebateCampaignId'],
        'campaign_name': value['campaignName'],
        'campaign_type_name': value['campaignTypeName'],
        'sup_con_sale': value['supConSale'],
        'sup_con_qty': value['supConQty'],
        'rebate_calculate_type': value['rebateCalculateType'],
        'actual_sale': value['actualSale'],
        'actual_qty': value['actualQty'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'con_period_start': value['conPeriodStart'] == null ? undefined : ((value['conPeriodStart']).toISOString()),
        'con_period_end': value['conPeriodEnd'] == null ? undefined : ((value['conPeriodEnd']).toISOString()),
        'est_rebate_amount': value['estRebateAmount'],
        'cn_dealer_create_list_id': value['cnDealerCreateListId'],
        'cn_no': value['cnNo'],
        'cn_date': value['cnDate'] == null ? undefined : ((value['cnDate']).toISOString()),
        'cn_amount': value['cnAmount'],
        'vat': value['vat'],
        'cn_amount_cur': value['cnAmountCur'],
        'vat_cur': value['vatCur'],
        'currency_id': value['currencyId'],
        'currency_abbr': value['currencyAbbr'],
        'exchange_rate': value['exchangeRate'],
        'customer_id': value['customerId'],
        'customer_code': value['customerCode'],
        'customer_name': value['customerName'],
        'tax_payer_id': value['taxPayerId'],
        'revenue_branch_code': value['revenueBranchCode'],
        'full_address': value['fullAddress'],
        'province_id': value['provinceId'],
        'province_name': value['provinceName'],
        'district_id': value['districtId'],
        'district_name': value['districtName'],
        'sub_district_id': value['subDistrictId'],
        'sub_district_name': value['subDistrictName'],
        'zip_code': value['zipCode'],
        'telephone': value['telephone'],
        'email': value['email'],
        'workflow_id': value['workflowId'],
        'current_step_id': value['currentStepId'],
        'trn_status': value['trnStatus'],
    };
}

