/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateActiveFlagMasterCustomerCreditScoreModel } from './UpdateActiveFlagMasterCustomerCreditScoreModel';
import {
    UpdateActiveFlagMasterCustomerCreditScoreModelFromJSON,
    UpdateActiveFlagMasterCustomerCreditScoreModelFromJSONTyped,
    UpdateActiveFlagMasterCustomerCreditScoreModelToJSON,
    UpdateActiveFlagMasterCustomerCreditScoreModelToJSONTyped,
} from './UpdateActiveFlagMasterCustomerCreditScoreModel';

/**
 * 
 * @export
 * @interface UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel
 */
export interface UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {UpdateActiveFlagMasterCustomerCreditScoreModel}
     * @memberof UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel
     */
    data?: UpdateActiveFlagMasterCustomerCreditScoreModel;
}

/**
 * Check if a given object implements the UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel interface.
 */
export function instanceOfUpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel(value: object): value is UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel {
    return true;
}

export function UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModelFromJSON(json: any): UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel {
    return UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModelFromJSONTyped(json, false);
}

export function UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'data': json['data'] == null ? undefined : UpdateActiveFlagMasterCustomerCreditScoreModelFromJSON(json['data']),
    };
}

export function UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModelToJSON(json: any): UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel {
    return UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModelToJSONTyped(json, false);
}

export function UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModelToJSONTyped(value?: UpdateActiveFlagMasterCustomerCreditScoreModelBaseResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'data': UpdateActiveFlagMasterCustomerCreditScoreModelToJSON(value['data']),
    };
}

