/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateActiveFlagMasterCustomerGradeModel } from './UpdateActiveFlagMasterCustomerGradeModel';
import {
    UpdateActiveFlagMasterCustomerGradeModelFromJSON,
    UpdateActiveFlagMasterCustomerGradeModelFromJSONTyped,
    UpdateActiveFlagMasterCustomerGradeModelToJSON,
    UpdateActiveFlagMasterCustomerGradeModelToJSONTyped,
} from './UpdateActiveFlagMasterCustomerGradeModel';

/**
 * 
 * @export
 * @interface UpdateActiveFlagMasterCustomerGradeModelBaseResponseModel
 */
export interface UpdateActiveFlagMasterCustomerGradeModelBaseResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateActiveFlagMasterCustomerGradeModelBaseResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateActiveFlagMasterCustomerGradeModelBaseResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateActiveFlagMasterCustomerGradeModelBaseResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {UpdateActiveFlagMasterCustomerGradeModel}
     * @memberof UpdateActiveFlagMasterCustomerGradeModelBaseResponseModel
     */
    data?: UpdateActiveFlagMasterCustomerGradeModel;
}

/**
 * Check if a given object implements the UpdateActiveFlagMasterCustomerGradeModelBaseResponseModel interface.
 */
export function instanceOfUpdateActiveFlagMasterCustomerGradeModelBaseResponseModel(value: object): value is UpdateActiveFlagMasterCustomerGradeModelBaseResponseModel {
    return true;
}

export function UpdateActiveFlagMasterCustomerGradeModelBaseResponseModelFromJSON(json: any): UpdateActiveFlagMasterCustomerGradeModelBaseResponseModel {
    return UpdateActiveFlagMasterCustomerGradeModelBaseResponseModelFromJSONTyped(json, false);
}

export function UpdateActiveFlagMasterCustomerGradeModelBaseResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateActiveFlagMasterCustomerGradeModelBaseResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'data': json['data'] == null ? undefined : UpdateActiveFlagMasterCustomerGradeModelFromJSON(json['data']),
    };
}

export function UpdateActiveFlagMasterCustomerGradeModelBaseResponseModelToJSON(json: any): UpdateActiveFlagMasterCustomerGradeModelBaseResponseModel {
    return UpdateActiveFlagMasterCustomerGradeModelBaseResponseModelToJSONTyped(json, false);
}

export function UpdateActiveFlagMasterCustomerGradeModelBaseResponseModelToJSONTyped(value?: UpdateActiveFlagMasterCustomerGradeModelBaseResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'data': UpdateActiveFlagMasterCustomerGradeModelToJSON(value['data']),
    };
}

