/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleModel } from './RoleModel';
import {
    RoleModelFromJSON,
    RoleModelFromJSONTyped,
    RoleModelToJSON,
    RoleModelToJSONTyped,
} from './RoleModel';
import type { DataAccessType } from './DataAccessType';
import {
    DataAccessTypeFromJSON,
    DataAccessTypeFromJSONTyped,
    DataAccessTypeToJSON,
    DataAccessTypeToJSONTyped,
} from './DataAccessType';
import type { UserType } from './UserType';
import {
    UserTypeFromJSON,
    UserTypeFromJSONTyped,
    UserTypeToJSON,
    UserTypeToJSONTyped,
} from './UserType';

/**
 * 
 * @export
 * @interface UserUpdateRequestModel
 */
export interface UserUpdateRequestModel {
    /**
     * 
     * @type {number}
     * @memberof UserUpdateRequestModel
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestModel
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestModel
     */
    password?: string;
    /**
     * 
     * @type {UserType}
     * @memberof UserUpdateRequestModel
     */
    userType?: UserType;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestModel
     */
    firstname?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestModel
     */
    lastname?: string;
    /**
     * 
     * @type {number}
     * @memberof UserUpdateRequestModel
     */
    businessRoleId?: number;
    /**
     * 
     * @type {number}
     * @memberof UserUpdateRequestModel
     */
    orgId?: number;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestModel
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestModel
     */
    mobilePhone?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestModel
     */
    employeeCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserUpdateRequestModel
     */
    activeFlag?: boolean;
    /**
     * 
     * @type {DataAccessType}
     * @memberof UserUpdateRequestModel
     */
    dataAccessType?: DataAccessType;
    /**
     * 
     * @type {Set<number>}
     * @memberof UserUpdateRequestModel
     */
    accessDepartment?: Set<number>;
    /**
     * 
     * @type {Array<RoleModel>}
     * @memberof UserUpdateRequestModel
     */
    roles?: Array<RoleModel>;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestModel
     */
    userProfilePath?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestModel
     */
    userSignaturePath?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRequestModel
     */
    userSignatureBase64?: string;
}



/**
 * Check if a given object implements the UserUpdateRequestModel interface.
 */
export function instanceOfUserUpdateRequestModel(value: object): value is UserUpdateRequestModel {
    return true;
}

export function UserUpdateRequestModelFromJSON(json: any): UserUpdateRequestModel {
    return UserUpdateRequestModelFromJSONTyped(json, false);
}

export function UserUpdateRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
        'userType': json['user_type'] == null ? undefined : UserTypeFromJSON(json['user_type']),
        'firstname': json['firstname'] == null ? undefined : json['firstname'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'businessRoleId': json['business_role_id'] == null ? undefined : json['business_role_id'],
        'orgId': json['org_id'] == null ? undefined : json['org_id'],
        'email': json['email'] == null ? undefined : json['email'],
        'mobilePhone': json['mobile_phone'] == null ? undefined : json['mobile_phone'],
        'employeeCode': json['employee_code'] == null ? undefined : json['employee_code'],
        'activeFlag': json['active_flag'] == null ? undefined : json['active_flag'],
        'dataAccessType': json['data_access_type'] == null ? undefined : DataAccessTypeFromJSON(json['data_access_type']),
        'accessDepartment': json['access_department'] == null ? undefined : new Set(json['access_department']),
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(RoleModelFromJSON)),
        'userProfilePath': json['user_profile_path'] == null ? undefined : json['user_profile_path'],
        'userSignaturePath': json['user_signature_path'] == null ? undefined : json['user_signature_path'],
        'userSignatureBase64': json['user_signature_base64'] == null ? undefined : json['user_signature_base64'],
    };
}

export function UserUpdateRequestModelToJSON(json: any): UserUpdateRequestModel {
    return UserUpdateRequestModelToJSONTyped(json, false);
}

export function UserUpdateRequestModelToJSONTyped(value?: UserUpdateRequestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'username': value['username'],
        'password': value['password'],
        'user_type': UserTypeToJSON(value['userType']),
        'firstname': value['firstname'],
        'lastname': value['lastname'],
        'business_role_id': value['businessRoleId'],
        'org_id': value['orgId'],
        'email': value['email'],
        'mobile_phone': value['mobilePhone'],
        'employee_code': value['employeeCode'],
        'active_flag': value['activeFlag'],
        'data_access_type': DataAccessTypeToJSON(value['dataAccessType']),
        'access_department': value['accessDepartment'] == null ? undefined : Array.from(value['accessDepartment'] as Set<any>),
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(RoleModelToJSON)),
        'user_profile_path': value['userProfilePath'],
        'user_signature_path': value['userSignaturePath'],
        'user_signature_base64': value['userSignatureBase64'],
    };
}

