/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VoucherMappingStatementModel
 */
export interface VoucherMappingStatementModel {
    /**
     * 
     * @type {number}
     * @memberof VoucherMappingStatementModel
     */
    mappingStmtId?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherMappingStatementModel
     */
    stmtId?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherMappingStatementModel
     */
    refSystemId?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherMappingStatementModel
     */
    mappingValue?: number;
}

/**
 * Check if a given object implements the VoucherMappingStatementModel interface.
 */
export function instanceOfVoucherMappingStatementModel(value: object): value is VoucherMappingStatementModel {
    return true;
}

export function VoucherMappingStatementModelFromJSON(json: any): VoucherMappingStatementModel {
    return VoucherMappingStatementModelFromJSONTyped(json, false);
}

export function VoucherMappingStatementModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoucherMappingStatementModel {
    if (json == null) {
        return json;
    }
    return {
        
        'mappingStmtId': json['mapping_stmt_id'] == null ? undefined : json['mapping_stmt_id'],
        'stmtId': json['stmt_id'] == null ? undefined : json['stmt_id'],
        'refSystemId': json['ref_system_id'] == null ? undefined : json['ref_system_id'],
        'mappingValue': json['mapping_value'] == null ? undefined : json['mapping_value'],
    };
}

export function VoucherMappingStatementModelToJSON(json: any): VoucherMappingStatementModel {
    return VoucherMappingStatementModelToJSONTyped(json, false);
}

export function VoucherMappingStatementModelToJSONTyped(value?: VoucherMappingStatementModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mapping_stmt_id': value['mappingStmtId'],
        'stmt_id': value['stmtId'],
        'ref_system_id': value['refSystemId'],
        'mapping_value': value['mappingValue'],
    };
}

