/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VoucherDetailModel
 */
export interface VoucherDetailModel {
    /**
     * 
     * @type {number}
     * @memberof VoucherDetailModel
     */
    trnVoucherDetailId?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherDetailModel
     */
    trnVoucherId?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherDetailModel
     */
    chartAccountsId?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherDetailModel
     */
    currencyId?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherDetailModel
     */
    exchangeRate?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherDetailModel
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof VoucherDetailModel
     */
    remark?: string;
    /**
     * 
     * @type {number}
     * @memberof VoucherDetailModel
     */
    depId?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherDetailModel
     */
    projectId?: number;
}

/**
 * Check if a given object implements the VoucherDetailModel interface.
 */
export function instanceOfVoucherDetailModel(value: object): value is VoucherDetailModel {
    return true;
}

export function VoucherDetailModelFromJSON(json: any): VoucherDetailModel {
    return VoucherDetailModelFromJSONTyped(json, false);
}

export function VoucherDetailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoucherDetailModel {
    if (json == null) {
        return json;
    }
    return {
        
        'trnVoucherDetailId': json['trn_voucher_detail_id'] == null ? undefined : json['trn_voucher_detail_id'],
        'trnVoucherId': json['trn_voucher_id'] == null ? undefined : json['trn_voucher_id'],
        'chartAccountsId': json['chart_accounts_id'] == null ? undefined : json['chart_accounts_id'],
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'exchangeRate': json['exchange_rate'] == null ? undefined : json['exchange_rate'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'remark': json['remark'] == null ? undefined : json['remark'],
        'depId': json['dep_id'] == null ? undefined : json['dep_id'],
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
    };
}

export function VoucherDetailModelToJSON(json: any): VoucherDetailModel {
    return VoucherDetailModelToJSONTyped(json, false);
}

export function VoucherDetailModelToJSONTyped(value?: VoucherDetailModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trn_voucher_detail_id': value['trnVoucherDetailId'],
        'trn_voucher_id': value['trnVoucherId'],
        'chart_accounts_id': value['chartAccountsId'],
        'currency_id': value['currencyId'],
        'exchange_rate': value['exchangeRate'],
        'amount': value['amount'],
        'remark': value['remark'],
        'dep_id': value['depId'],
        'project_id': value['projectId'],
    };
}

