/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowTransitionResult } from './WorkflowTransitionResult';
import {
    WorkflowTransitionResultFromJSON,
    WorkflowTransitionResultFromJSONTyped,
    WorkflowTransitionResultToJSON,
    WorkflowTransitionResultToJSONTyped,
} from './WorkflowTransitionResult';

/**
 * 
 * @export
 * @interface WorkflowTransitionResultBaseResponseModel
 */
export interface WorkflowTransitionResultBaseResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof WorkflowTransitionResultBaseResponseModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkflowTransitionResultBaseResponseModel
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowTransitionResultBaseResponseModel
     */
    statusCode?: number;
    /**
     * 
     * @type {WorkflowTransitionResult}
     * @memberof WorkflowTransitionResultBaseResponseModel
     */
    data?: WorkflowTransitionResult;
}

/**
 * Check if a given object implements the WorkflowTransitionResultBaseResponseModel interface.
 */
export function instanceOfWorkflowTransitionResultBaseResponseModel(value: object): value is WorkflowTransitionResultBaseResponseModel {
    return true;
}

export function WorkflowTransitionResultBaseResponseModelFromJSON(json: any): WorkflowTransitionResultBaseResponseModel {
    return WorkflowTransitionResultBaseResponseModelFromJSONTyped(json, false);
}

export function WorkflowTransitionResultBaseResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowTransitionResultBaseResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'data': json['data'] == null ? undefined : WorkflowTransitionResultFromJSON(json['data']),
    };
}

export function WorkflowTransitionResultBaseResponseModelToJSON(json: any): WorkflowTransitionResultBaseResponseModel {
    return WorkflowTransitionResultBaseResponseModelToJSONTyped(json, false);
}

export function WorkflowTransitionResultBaseResponseModelToJSONTyped(value?: WorkflowTransitionResultBaseResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'statusCode': value['statusCode'],
        'data': WorkflowTransitionResultToJSON(value['data']),
    };
}

