/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkFlowRefType } from './WorkFlowRefType';
import {
    WorkFlowRefTypeFromJSON,
    WorkFlowRefTypeFromJSONTyped,
    WorkFlowRefTypeToJSON,
    WorkFlowRefTypeToJSONTyped,
} from './WorkFlowRefType';

/**
 * 
 * @export
 * @interface WorkflowTransitionInfoModel
 */
export interface WorkflowTransitionInfoModel {
    /**
     * 
     * @type {WorkFlowRefType}
     * @memberof WorkflowTransitionInfoModel
     */
    workflowRefType?: WorkFlowRefType;
    /**
     * 
     * @type {number}
     * @memberof WorkflowTransitionInfoModel
     */
    transitionId?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowTransitionInfoModel
     */
    currentStepId?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowTransitionInfoModel
     */
    targetStepId?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowTransitionInfoModel
     */
    targetStepType?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowTransitionInfoModel
     */
    targetStepName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WorkflowTransitionInfoModel
     */
    requiredSave?: boolean;
}



/**
 * Check if a given object implements the WorkflowTransitionInfoModel interface.
 */
export function instanceOfWorkflowTransitionInfoModel(value: object): value is WorkflowTransitionInfoModel {
    return true;
}

export function WorkflowTransitionInfoModelFromJSON(json: any): WorkflowTransitionInfoModel {
    return WorkflowTransitionInfoModelFromJSONTyped(json, false);
}

export function WorkflowTransitionInfoModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowTransitionInfoModel {
    if (json == null) {
        return json;
    }
    return {
        
        'workflowRefType': json['workflow_ref_type'] == null ? undefined : WorkFlowRefTypeFromJSON(json['workflow_ref_type']),
        'transitionId': json['transition_id'] == null ? undefined : json['transition_id'],
        'currentStepId': json['current_step_id'] == null ? undefined : json['current_step_id'],
        'targetStepId': json['target_step_id'] == null ? undefined : json['target_step_id'],
        'targetStepType': json['target_step_type'] == null ? undefined : json['target_step_type'],
        'targetStepName': json['target_step_name'] == null ? undefined : json['target_step_name'],
        'requiredSave': json['required_save'] == null ? undefined : json['required_save'],
    };
}

export function WorkflowTransitionInfoModelToJSON(json: any): WorkflowTransitionInfoModel {
    return WorkflowTransitionInfoModelToJSONTyped(json, false);
}

export function WorkflowTransitionInfoModelToJSONTyped(value?: WorkflowTransitionInfoModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workflow_ref_type': WorkFlowRefTypeToJSON(value['workflowRefType']),
        'transition_id': value['transitionId'],
        'current_step_id': value['currentStepId'],
        'target_step_id': value['targetStepId'],
        'target_step_type': value['targetStepType'],
        'target_step_name': value['targetStepName'],
        'required_save': value['requiredSave'],
    };
}

