/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WorkFlowRefType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_11: 11,
    NUMBER_12: 12,
    NUMBER_13: 13,
    NUMBER_14: 14,
    NUMBER_15: 15,
    NUMBER_16: 16,
    NUMBER_17: 17,
    NUMBER_18: 18,
    NUMBER_19: 19,
    NUMBER_20: 20,
    NUMBER_21: 21
} as const;
export type WorkFlowRefType = typeof WorkFlowRefType[keyof typeof WorkFlowRefType];


export function instanceOfWorkFlowRefType(value: any): boolean {
    for (const key in WorkFlowRefType) {
        if (Object.prototype.hasOwnProperty.call(WorkFlowRefType, key)) {
            if (WorkFlowRefType[key as keyof typeof WorkFlowRefType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WorkFlowRefTypeFromJSON(json: any): WorkFlowRefType {
    return WorkFlowRefTypeFromJSONTyped(json, false);
}

export function WorkFlowRefTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkFlowRefType {
    return json as WorkFlowRefType;
}

export function WorkFlowRefTypeToJSON(value?: WorkFlowRefType | null): any {
    return value as any;
}

export function WorkFlowRefTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkFlowRefType {
    return value as WorkFlowRefType;
}

