/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApprovalARCNInHouseDetail,
  ApprovalARCNInHouseDetailBaseResponseModel,
  ApprovalARCNInHouseResponseModel,
} from '../models/index';
import {
    ApprovalARCNInHouseDetailFromJSON,
    ApprovalARCNInHouseDetailToJSON,
    ApprovalARCNInHouseDetailBaseResponseModelFromJSON,
    ApprovalARCNInHouseDetailBaseResponseModelToJSON,
    ApprovalARCNInHouseResponseModelFromJSON,
    ApprovalARCNInHouseResponseModelToJSON,
} from '../models/index';

export interface ApiApprovalARCNInHouseDetailIdGetRequest {
    id: number;
}

export interface ApiApprovalARCNInHouseListGetRequest {
    rebateCode?: string;
    customerCode?: string;
    startDate?: Date;
    endDate?: Date;
    currentStepId?: number;
    pageIndex?: number;
    pageSize?: number;
}

export interface ApiApprovalARCNInHouseUpdatePostRequest {
    body?: ApprovalARCNInHouseDetail;
}

/**
 * 
 */
export class ApprovalARCNInHouseApi extends runtime.BaseAPI {

    /**
     */
    async apiApprovalARCNInHouseDetailIdGetRaw(requestParameters: ApiApprovalARCNInHouseDetailIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApprovalARCNInHouseDetailBaseResponseModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiApprovalARCNInHouseDetailIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // oauth2 authentication
        }

        const response = await this.request({
            path: `/api/ApprovalARCNInHouse/detail/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApprovalARCNInHouseDetailBaseResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async apiApprovalARCNInHouseDetailIdGet(requestParameters: ApiApprovalARCNInHouseDetailIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApprovalARCNInHouseDetailBaseResponseModel> {
        const response = await this.apiApprovalARCNInHouseDetailIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiApprovalARCNInHouseListGetRaw(requestParameters: ApiApprovalARCNInHouseListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApprovalARCNInHouseResponseModel>> {
        const queryParameters: any = {};

        if (requestParameters['rebateCode'] != null) {
            queryParameters['rebate_code'] = requestParameters['rebateCode'];
        }

        if (requestParameters['customerCode'] != null) {
            queryParameters['customer_code'] = requestParameters['customerCode'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['start_date'] = (requestParameters['startDate'] as any).toISOString();
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['end_date'] = (requestParameters['endDate'] as any).toISOString();
        }

        if (requestParameters['currentStepId'] != null) {
            queryParameters['current_step_id'] = requestParameters['currentStepId'];
        }

        if (requestParameters['pageIndex'] != null) {
            queryParameters['pageIndex'] = requestParameters['pageIndex'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // oauth2 authentication
        }

        const response = await this.request({
            path: `/api/ApprovalARCNInHouse/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApprovalARCNInHouseResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async apiApprovalARCNInHouseListGet(requestParameters: ApiApprovalARCNInHouseListGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApprovalARCNInHouseResponseModel> {
        const response = await this.apiApprovalARCNInHouseListGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiApprovalARCNInHouseUpdatePostRaw(requestParameters: ApiApprovalARCNInHouseUpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApprovalARCNInHouseDetailBaseResponseModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // oauth2 authentication
        }

        const response = await this.request({
            path: `/api/ApprovalARCNInHouse/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApprovalARCNInHouseDetailToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApprovalARCNInHouseDetailBaseResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async apiApprovalARCNInHouseUpdatePost(requestParameters: ApiApprovalARCNInHouseUpdatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApprovalARCNInHouseDetailBaseResponseModel> {
        const response = await this.apiApprovalARCNInHouseUpdatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
