/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApprovalARCNRebateDetailModel,
  ApprovalARCNRebateDetailModelBaseResponseModel,
  ApprovalARCNRebateResponseModel,
} from '../models/index';
import {
    ApprovalARCNRebateDetailModelFromJSON,
    ApprovalARCNRebateDetailModelToJSON,
    ApprovalARCNRebateDetailModelBaseResponseModelFromJSON,
    ApprovalARCNRebateDetailModelBaseResponseModelToJSON,
    ApprovalARCNRebateResponseModelFromJSON,
    ApprovalARCNRebateResponseModelToJSON,
} from '../models/index';

export interface ApiApprovalARCNRebateDetailIdGetRequest {
    id: number;
}

export interface ApiApprovalARCNRebateListGetRequest {
    rebateCode?: string;
    customerCode?: string;
    brandId?: number;
    startDate?: Date;
    endDate?: Date;
    currentStepId?: number;
    pageIndex?: number;
    pageSize?: number;
}

export interface ApiApprovalARCNRebateUpdatePostRequest {
    body?: ApprovalARCNRebateDetailModel;
}

/**
 * 
 */
export class ApprovalARCNRebateApi extends runtime.BaseAPI {

    /**
     */
    async apiApprovalARCNRebateDetailIdGetRaw(requestParameters: ApiApprovalARCNRebateDetailIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApprovalARCNRebateDetailModelBaseResponseModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiApprovalARCNRebateDetailIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // oauth2 authentication
        }

        const response = await this.request({
            path: `/api/ApprovalARCNRebate/detail/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApprovalARCNRebateDetailModelBaseResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async apiApprovalARCNRebateDetailIdGet(requestParameters: ApiApprovalARCNRebateDetailIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApprovalARCNRebateDetailModelBaseResponseModel> {
        const response = await this.apiApprovalARCNRebateDetailIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiApprovalARCNRebateListGetRaw(requestParameters: ApiApprovalARCNRebateListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApprovalARCNRebateResponseModel>> {
        const queryParameters: any = {};

        if (requestParameters['rebateCode'] != null) {
            queryParameters['rebate_code'] = requestParameters['rebateCode'];
        }

        if (requestParameters['customerCode'] != null) {
            queryParameters['customer_code'] = requestParameters['customerCode'];
        }

        if (requestParameters['brandId'] != null) {
            queryParameters['brand_id'] = requestParameters['brandId'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['start_date'] = (requestParameters['startDate'] as any).toISOString();
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['end_date'] = (requestParameters['endDate'] as any).toISOString();
        }

        if (requestParameters['currentStepId'] != null) {
            queryParameters['current_step_id'] = requestParameters['currentStepId'];
        }

        if (requestParameters['pageIndex'] != null) {
            queryParameters['pageIndex'] = requestParameters['pageIndex'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // oauth2 authentication
        }

        const response = await this.request({
            path: `/api/ApprovalARCNRebate/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApprovalARCNRebateResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async apiApprovalARCNRebateListGet(requestParameters: ApiApprovalARCNRebateListGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApprovalARCNRebateResponseModel> {
        const response = await this.apiApprovalARCNRebateListGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiApprovalARCNRebateUpdatePostRaw(requestParameters: ApiApprovalARCNRebateUpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApprovalARCNRebateDetailModelBaseResponseModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // oauth2 authentication
        }

        const response = await this.request({
            path: `/api/ApprovalARCNRebate/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApprovalARCNRebateDetailModelToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApprovalARCNRebateDetailModelBaseResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async apiApprovalARCNRebateUpdatePost(requestParameters: ApiApprovalARCNRebateUpdatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApprovalARCNRebateDetailModelBaseResponseModel> {
        const response = await this.apiApprovalARCNRebateUpdatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
