/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClaimCNPaymentModelListBaseResponseModel,
  ClaimCNRequestModel,
  StringBaseResponseModel,
} from '../models/index';

export interface ApiClaimCNCreateClaimCnPostRequest {
    body?: Array<ClaimCNRequestModel>;
}

/**
 * ClaimCNApi - interface
 * 
 * @export
 * @interface ClaimCNApiInterface
 */
export interface ClaimCNApiInterface {
    /**
     * 
     * @param {Array<ClaimCNRequestModel>} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClaimCNApiInterface
     */
    apiClaimCNCreateClaimCnPostRaw(requestParameters: ApiClaimCNCreateClaimCnPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringBaseResponseModel>>;

    /**
     */
    apiClaimCNCreateClaimCnPost(requestParameters: ApiClaimCNCreateClaimCnPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringBaseResponseModel>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClaimCNApiInterface
     */
    apiClaimCNGetClaimCnGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClaimCNPaymentModelListBaseResponseModel>>;

    /**
     */
    apiClaimCNGetClaimCnGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClaimCNPaymentModelListBaseResponseModel>;

}

/**
 * 
 */
export class ClaimCNApi extends runtime.BaseAPI implements ClaimCNApiInterface {

    /**
     */
    async apiClaimCNCreateClaimCnPostRaw(requestParameters: ApiClaimCNCreateClaimCnPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringBaseResponseModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/ClaimCN/create-claim-cn`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async apiClaimCNCreateClaimCnPost(requestParameters: ApiClaimCNCreateClaimCnPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringBaseResponseModel> {
        const response = await this.apiClaimCNCreateClaimCnPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiClaimCNGetClaimCnGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClaimCNPaymentModelListBaseResponseModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/ClaimCN/get-claim-cn`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async apiClaimCNGetClaimCnGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClaimCNPaymentModelListBaseResponseModel> {
        const response = await this.apiClaimCNGetClaimCnGetRaw(initOverrides);
        return await response.value();
    }

}
