/* tslint:disable */
/* eslint-disable */
/**
 * BaseWebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateOMSopRequestModel,
  StringBaseResponseModel,
} from '../models/index';
import {
    CreateOMSopRequestModelFromJSON,
    CreateOMSopRequestModelToJSON,
    StringBaseResponseModelFromJSON,
    StringBaseResponseModelToJSON,
} from '../models/index';

export interface ApiOMSopCreateSopPostRequest {
    body?: Array<CreateOMSopRequestModel>;
}

/**
 * 
 */
export class OMSopApi extends runtime.BaseAPI {

    /**
     */
    async apiOMSopCreateSopPostRaw(requestParameters: ApiOMSopCreateSopPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringBaseResponseModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/OMSop/create-sop`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body']!.map(CreateOMSopRequestModelToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringBaseResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async apiOMSopCreateSopPost(requestParameters: ApiOMSopCreateSopPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringBaseResponseModel> {
        const response = await this.apiOMSopCreateSopPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
