/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseResponseModel
 */
export interface BaseResponseModel {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseModel
     */
    fileName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BaseResponseModel
     */
    fileExtension?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseModel
     */
    urlDownload?: string;
}

/**
 * Check if a given object implements the BaseResponseModel interface.
 */
export function instanceOfBaseResponseModel(value: object): value is BaseResponseModel {
    return true;
}

export function BaseResponseModelFromJSON(json: any): BaseResponseModel {
    return BaseResponseModelFromJSONTyped(json, false);
}

export function BaseResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'fileExtension': json['fileExtension'] == null ? undefined : json['fileExtension'],
        'urlDownload': json['url_download'] == null ? undefined : json['url_download'],
    };
}

export function BaseResponseModelToJSON(json: any): BaseResponseModel {
    return BaseResponseModelToJSONTyped(json, false);
}

export function BaseResponseModelToJSONTyped(value?: BaseResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileName': value['fileName'],
        'fileExtension': value['fileExtension'],
        'url_download': value['urlDownload'],
    };
}

